import { StoreType, ViewModeType } from 'constants/types';

const prefix = 'abo';

export const ALBERTO_BINI_OUTLET = {
    active: true,
    URL: ['https://alberto-bini-outlet.netlify.app'],
    appStoreUrl: null,
    playMarketUrl: null,
    web_lang: 'uk', // html lang
    store_name: 'Alberto Bini Outlet',
    store_code: 'ALBERTO_BINI_SALES',
    token_key: `${prefix}-tkn`,
    cart_key: `${prefix}-cart`,
    favorite_url: `${prefix}-favorites`,
    base_url: 'https://kremen-belts.com/api',
    lang_key: `${prefix}-lang`,
    app_lang: 'ua',
    links: [],
    options: {
        product_image_options: { width: 6, height: 9 },
        main_price_multiplication: 3,
        sale_price_multiplication: 2,
        currency_multiplication: 40,
        custom_currency: '₴',
        store_type: StoreType?.sales,
        home_page_active: false,
        custom_logo: false,
        plan_options: {
            prices: true,
            sizes: true,
            contacts: true,
            categories: true,
            productShare: true,
            cart: true,
            favorites: true,
            video: false,
            tableSizes: true,
            platformAvailable: true,
            appleStore: false,
            playMarket: false,
            admins: 5,
            products: 200,
            productModels: 10,
            photos: 10,
            videos: null,
        },
    },
    web_head_data: {
        store_title: 'Alberto Bini Каталог | Alberto Bini Outlet Catalog ',
        store_description: `Ласкаво просимо до Alberto Bini — світу вишуканого жіночого верхнього одягу! Дослідіть наш широкий вибір високоякісних стильних пальт, тренчів та курток. Погрузіться в унікальний стиль та комфорт з Alberto Bini!  Welcome to Alberto Bini — the world of exquisite women's outerwear! Explore our wide selection of high-quality stylish coats, trenches, and jackets. Immerse yourself in unique style and comfort with Alberto Bini!`,
        google_analytics_id: 'G-C4TDRX7K5V',
        store_logo: 'alberto_bini_logo.png',
    },
    user_options: { view_mode: ViewModeType?.card },
};
