import { StoreType, ViewModeType } from 'constants/types';

const prefix = 'kbs';

export const KREMEN_BELTS_SALES = {
    active: true,
    required_registration: false,
    URL: ['https://kremen-belts-sales.netlify.app'],
    appStoreUrl: null,
    playMarketUrl: null,
    web_lang: 'uk', // html lang
    store_name: 'Kremen Belts Sales',
    store_code: 'kremen_belts_sales',
    token_key: `${prefix}-tkn`,
    cart_key: `${prefix}-cart`,
    favorite_url: `${prefix}-favorites`,
    base_url: 'https://kremen-belts.com/api',
    lang_key: `${prefix}-lang`,
    app_lang: 'ua',
    links: [{ name: 'Kremen Belts', href: 'https://kremen-belts.netlify.app', description: 'WEB' }],
    options: {
        product_image_options: { width: 3, height: 2 },
        main_price_multiplication: 1,
        sale_price_multiplication: 1,
        currency_multiplication: 1,
        custom_currency: null,
        min_items_to_buy: 1,
        store_type: StoreType?.sales,
        home_page_active: false,
        informative_page_active: false,
        custom_logo: false,
        plan_options: {
            prices: true,
            sizes: false,
            contacts: true,
            categories: true,
            productShare: true,
            cart: true,
            favorites: true,
            video: false,
            tableSizes: false,
            platformAvailable: false,
            appleStore: false,
            playMarket: false,
            admins: 3,
            products: 200,
            productModels: 10,
            photos: 10,
            videos: null,
        },
    },
    web_head_data: {
        store_title: ' Kremen Belts Оптовий Каталог | Kremen Belts Wholesales Catalog',
        store_description: `Ласкаво просимо до Kremen Belts — вашого найкращого джерела стильних ременів та аксесуарів! | Welcome to Kremen Belts — your ultimate source for stylish belts and accessories!`,
        google_analytics_id: 'G-7G98583PY1',
        store_logo: 'kremen_belts_logo.png',
    },
    user_options: { view_mode: ViewModeType?.card },
};
