import { StoreType, ViewModeType } from 'store_constants/types';

const prefix = 'abm';

export const ALBERTO_BINI_MAIN = {
    active: true, // Поле которое запускает магазин true - работает false - остановлен / по тех. причина
    required_registration: false,
    URL: ['https://alberto-bini.netlify.app'],
    appStoreUrl: null,
    playMarketUrl: null,
    web_lang: 'uk', // html lang
    store_name: 'Alberto Bini',
    store_code: 'ALBERTO_BINI',
    token_key: `${prefix}-tkn`,
    cart_key: `${prefix}-cart`,
    favorite_url: `${prefix}-favorites`,
    base_url: 'https://kremen-belts.com/api',
    lang_key: `${prefix}-lang`,
    app_lang: 'ua',
    supported_countries: [{ code: 'UA', country: 'ukraine' }],
    links: [],
    options: {
        product_image_options: { width: 6, height: 9 },
        main_price_multiplication: 1,
        sale_price_multiplication: 1,
        currency_multiplication: 1,
        retail_price_multiplication: 1,
        custom_currency: '$',
        min_items_to_buy: 1,
        store_type: StoreType?.default,
        home_page_active: true,
        informative_page_active: true,
        custom_logo: true,
        plan_options: {
            prices: true,
            sizes: true,
            contacts: true,
            categories: true,
            productShare: true,
            cart: true,
            favorites: true,
            video: false,
            tableSizes: true,
            platformAvailable: true,
            appleStore: false,
            playMarket: false,
            admins: 5,
            products: 200,
            productModels: 10,
            photos: 10,
            videos: null,
        },
    },
    web_head_data: {
        store_title: 'Alberto Bini Wholesales Catalog | Alberto Bini Оптовий Каталог',
        store_description: `Ласкаво просимо до Alberto Bini — світу вишуканого жіночого верхнього одягу! Дослідіть наш широкий вибір високоякісних стильних пальт, тренчів та курток. Погрузіться в унікальний стиль та комфорт з Alberto Bini!  Welcome to Alberto Bini — the world of exquisite women's outerwear! Explore our wide selection of high-quality stylish coats, trenches, and jackets. Immerse yourself in unique style and comfort with Alberto Bini!`,
        google_analytics_id: 'G-C4TDRX7K5V',
        store_logo: 'alberto_bini_logo.png',
    },
    user_options: { view_mode: ViewModeType?.card },
};
