import { useEffect, useState } from 'react';

export const useGetLanguage = ({ lang }) => {
    const [currentLanguage, setCurrentLanguage] = useState({ code: '', string: {} });

    const langList = [
        {
            code: 'en',
            string: {
                shown: 'Shown',
                call_back_messageA:
                    'Hello! If you have questions, comments or need assistance, please contact us. We are ready to help you with your choice, provide you with additional information about the product or help you place your order.',

                call_back_messageB: 'You can contact us in any messenger available or by phone.',
                call_back_messageC: 'Thank you for your interest in our online catalogue!',
                languages: 'Languages',
                back_to_stores: 'Back to stores',
                ok: 'Ok',
                search: 'Search',
                language: 'language',
                wrong_key: 'Wrong key!',
                approve: 'Approve',
                ready: 'Ready',
                clear_filters: 'Clear filters',
                clear: 'Clear',
                filters: 'Filters',
                nothing_was_found: 'Nothing was found',
                stores: 'Stores',
                catalog: 'Catalog',
                polish: 'Polish',
                czech: 'Czech',
                russian: 'Russian',
                ukrainian: 'Ukrainian',
                english: 'English',
                find_store_by_name: 'Find store by name',
                favorites: 'Favorites',
                my_stores: 'My stores',
                login: 'Login',
                register: 'Register',
                wrong_login_or_password: 'Wrong login or password',
                forgot_password: 'Forgot password?',
                cart: 'Cart',
                vendor_code: 'Vendor code',
                price: 'Price',
                logout: 'Logout',
                submit: 'Submit',
                ukraine: 'Ukraine',
                czechia: 'Czechia',
                italy: 'Italy',
                kazakhstan: 'Kazakhstan',
                poland: 'Poland',
                turkey: 'Turkey',
                description: 'Description',
                added: 'Added',
                add_to: 'Add To',
                first_name: 'First Name',
                last_name: 'Last Name',
                phone_number: 'Phone Number',
                city: 'City',
                email: 'Email',
                password: 'Password',
                confirm_password: 'Confirm password',
                company_name: 'Company Name',
                already_registered: 'Already registered',
                do_want_to_logout: 'Are you sure you want to leave your account?',
                cancel: 'Cancel',
                clear_cart: 'Clear cart',
                do_you_want_to_clear_cart: 'Do you want to clear cart?',
                enter_password: 'Enter password',
                enter_email: 'Enter email',
                enter_valid_email: 'Enter valid email',
                password_length_min_8_symbols: 'Password length min 8 symbols',
                passwords_do_not_match: 'Passwords do not match',
                enter_first_name: 'Enter first name',
                enter_last_name: 'Enter last name',
                enter_phone_number: 'Enter phone number',
                my_profile: 'My profile',
                country: 'Country',
                e_a: 'e.a.',
                reset_password: 'Reset Password',
                close: 'Close',
                please_enter_your_email_address_you_will_receive_a_link_to_create_a_new_password_via_email:
                    'Please enter your email address. You will receive a link to create a new password via email.',
                user_with_this_email_not_found: 'User with this email not found',
                an_email_with_a_link_has_been_sent_to_your_email: 'An email with a link has been sent to your email',
                find_by_vendor_code: 'Find by vendor code',
                colors: 'Colors',
                sizes: 'Sizes',
                contacts: 'Contacts',
                name: 'Name',
                no_results: 'No results',
                loading: 'Loading',
                phone_length_minimum_7_characters: 'Phone length minimum 7 characters',
                sizes_table: 'Sizes table',
                load_more: 'Load more',
                out_of: 'out of',
                models: 'models',
                in_order_to_use_this_option_you_must_log_in_or_register:
                    'In order to use this option, you must log in or register.',
                you_need_to_login: 'You need to login!',
                sended: 'Sended',
                store_key: 'Store key',
                enter_store_key: 'Enter store key!',
                this_catalog_is_private_in_order_to_enter_you_must_enter_the_key:
                    'This catalog is private, in order to enter you must enter the key.',
                this_catalog_does_not_support_the_current_language_to_continue_select_a_language_from_the_list_in_the_languages_menu:
                    'This catalog does not support the current language, to continue, select a language from the list in the languages ​​menu',
                language_error: 'Language error!',
                spanish: 'Spain',
                french: 'French',
            },
        },
        {
            code: 'fr',
            string: {
                show: 'Shown',
                call_back_messageA:
                    'Hello! If you have questions, comments or need assistance, please contact us. We are ready to help you with your choice, provide you with additional information about the product or help you place your order.',

                call_back_messageB: 'You can contact us in any messenger available or by phone.',
                call_back_messageC: 'Thank you for your interest in our online catalogue!',
                languages: 'Languages',
                back_to_stores: 'Back to stores',
                ok: 'Ok',
                search: 'Search',
                language: 'language',
                wrong_key: 'Wrong key!',
                approve: 'Approve',
                ready: 'Ready',
                clear_filters: 'Clear filters',
                clear: 'Clear',
                filters: 'Filters',
                nothing_was_found: 'Nothing was found',
                stores: 'Stores',
                catalog: 'Catalog',
                polish: 'Polish',
                czech: 'Czech',
                russian: 'Russian',
                ukrainian: 'Ukrainian',
                english: 'English',
                find_store_by_name: 'Find store by name',
                favorites: 'Favorites',
                my_stores: 'My stores',
                login: 'Login',
                register: 'Register',
                wrong_login_or_password: 'Wrong login or password',
                forgot_password: 'Forgot password?',
                cart: 'Cart',
                vendor_code: 'Vendor code',
                // color: 'Color',
                // available_sizes: 'Available sizes',
                // go_to_details: 'Go to details',
                // remove: 'Remove',
                price: 'Price',
                // total_price: 'Total price',
                // total_quantity: 'Total quantity',
                // add_product_sizes: 'Add Product Sizes',
                // gallery: 'Gallery',
                // admin: 'Admin',
                logout: 'Logout',
                submit: 'Submit',
                ukraine: 'Ukraine',
                czechia: 'Czechia',
                italy: 'Italy',
                kazakhstan: 'Kazakhstan',
                poland: 'Poland',
                turkey: 'Turkey',
                description: 'Description',
                added: 'Added',
                add_to: 'Add To',
                // confirm_order: 'Confirm Order',
                // personal_data: 'Personal Data',
                first_name: 'First Name',
                last_name: 'Last Name',
                // receiver_first_name: 'Receiver First Name',
                // receiver_last_name: 'Receiver Last Name',
                // receiver_phone_number: 'Receiver Phone Number',
                phone_number: 'Phone Number',
                city: 'City',
                email: 'Email',
                password: 'Password',
                confirm_password: 'Confirm password',
                company_name: 'Company Name',
                already_registered: 'Already registered',
                do_want_to_logout: 'Are you sure you want to leave your account?',
                // delivery_information: 'Delivery Information',
                // additional_information: 'Additional Information',
                // post_office: 'Post Office',
                // comments: 'Comments',
                // status: 'Status',
                // ordered_date: 'Ordered Date',
                // delete_item: 'Delete Item',
                // do_you_want_to_delete_item: 'Do you want to delete item?',
                cancel: 'Cancel',
                // confirm: 'Confirm',
                // do_you_want_to_confirm_order: 'Do you want to confirm order?',
                // order: 'Order',
                clear_cart: 'Clear cart',
                do_you_want_to_clear_cart: 'Do you want to clear cart?',
                // clear_favorites: 'Clear favorites',
                // do_you_want_to_clear_favorites: 'Do you want to clear favorites?',
                // promo_code: 'Promo Code',
                enter_password: 'Enter password',
                enter_email: 'Enter email',
                enter_valid_email: 'Enter valid email',
                password_length_min_8_symbols: 'Password length min 8 symbols',
                passwords_do_not_match: 'Passwords do not match',
                enter_first_name: 'Enter first name',
                enter_last_name: 'Enter last name',
                enter_phone_number: 'Enter phone number',
                // login_to_order: 'Login to order',
                // my_orders: 'My orders',
                my_profile: 'My profile',
                // price_per_item: 'Price per item',
                country: 'Country',
                e_a: 'e.a.',
                reset_password: 'Reset Password',
                close: 'Close',
                please_enter_your_email_address_you_will_receive_a_link_to_create_a_new_password_via_email:
                    'Please enter your email address. You will receive a link to create a new password via email.',
                user_with_this_email_not_found: 'User with this email not found',
                an_email_with_a_link_has_been_sent_to_your_email: 'An email with a link has been sent to your email',
                find_by_vendor_code: 'Find by vendor code',
                colors: 'Colors',
                sizes: 'Sizes',
                contacts: 'Contacts',
                name: 'Name',
                no_results: 'No results',
                loading: 'Loading',
                phone_length_minimum_7_characters: 'Phone length minimum 7 characters',
                // your_order_may_take_some_time_to_process: 'Your order may take some time to process',
                sizes_table: 'Sizes table',
                load_more: 'Load more',
                out_of: 'out of',
                models: 'models',
                in_order_to_use_this_option_you_must_log_in_or_register:
                    'In order to use this option, you must log in or register.',
                you_need_to_login: 'You need to login!',
                sended: 'Sended',
                store_key: 'Store key',
                enter_store_key: 'Enter store key!',
                this_catalog_is_private_in_order_to_enter_you_must_enter_the_key:
                    'This catalog is private, in order to enter you must enter the key.',
                this_catalog_does_not_support_the_current_language_to_continue_select_a_language_from_the_list_in_the_languages_menu:
                    'This catalog does not support the current language, to continue, select a language from the list in the languages ​​menu',
                language_error: 'Language error!',
                spanish: 'Spain',
                french: 'French',
            },
        },
        {
            code: 'es',
            string: {
                show: 'Shown',
                call_back_messageA:
                    'Hello! If you have questions, comments or need assistance, please contact us. We are ready to help you with your choice, provide you with additional information about the product or help you place your order.',

                call_back_messageB: 'You can contact us in any messenger available or by phone.',
                call_back_messageC: 'Thank you for your interest in our online catalogue!',
                languages: 'Languages',
                back_to_stores: 'Back to stores',
                ok: 'Ok',
                search: 'Search',
                language: 'language',
                wrong_key: 'Wrong key!',
                approve: 'Approve',
                ready: 'Ready',
                clear_filters: 'Clear filters',
                clear: 'Clear',
                filters: 'Filters',
                nothing_was_found: 'Nothing was found',
                stores: 'Stores',
                catalog: 'Catalog',
                polish: 'Polish',
                czech: 'Czech',
                russian: 'Russian',
                ukrainian: 'Ukrainian',
                english: 'English',
                find_store_by_name: 'Find store by name',
                favorites: 'Favorites',
                my_stores: 'My stores',
                login: 'Login',
                register: 'Register',
                wrong_login_or_password: 'Wrong login or password',
                forgot_password: 'Forgot password?',
                cart: 'Cart',
                vendor_code: 'Vendor code',
                price: 'Price',
                logout: 'Logout',
                submit: 'Submit',
                ukraine: 'Ukraine',
                czechia: 'Czechia',
                italy: 'Italy',
                kazakhstan: 'Kazakhstan',
                poland: 'Poland',
                turkey: 'Turkey',
                description: 'Description',
                added: 'Added',
                add_to: 'Add To',
                // confirm_order: 'Confirm Order',
                // personal_data: 'Personal Data',
                first_name: 'First Name',
                last_name: 'Last Name',
                // receiver_first_name: 'Receiver First Name',
                // receiver_last_name: 'Receiver Last Name',
                // receiver_phone_number: 'Receiver Phone Number',
                phone_number: 'Phone Number',
                city: 'City',
                email: 'Email',
                password: 'Password',
                confirm_password: 'Confirm password',
                company_name: 'Company Name',
                already_registered: 'Already registered',
                do_want_to_logout: 'Are you sure you want to leave your account?',
                cancel: 'Cancel',
                // confirm: 'Confirm',
                // do_you_want_to_confirm_order: 'Do you want to confirm order?',
                // order: 'Order',
                clear_cart: 'Clear cart',
                do_you_want_to_clear_cart: 'Do you want to clear cart?',
                // clear_favorites: 'Clear favorites',
                // do_you_want_to_clear_favorites: 'Do you want to clear favorites?',
                // promo_code: 'Promo Code',
                enter_password: 'Enter password',
                enter_email: 'Enter email',
                enter_valid_email: 'Enter valid email',
                password_length_min_8_symbols: 'Password length min 8 symbols',
                passwords_do_not_match: 'Passwords do not match',
                enter_first_name: 'Enter first name',
                enter_last_name: 'Enter last name',
                enter_phone_number: 'Enter phone number',
                // login_to_order: 'Login to order',
                // my_orders: 'My orders',
                my_profile: 'My profile',
                // price_per_item: 'Price per item',
                country: 'Country',
                e_a: 'e.a.',
                reset_password: 'Reset Password',
                close: 'Close',
                please_enter_your_email_address_you_will_receive_a_link_to_create_a_new_password_via_email:
                    'Please enter your email address. You will receive a link to create a new password via email.',
                user_with_this_email_not_found: 'User with this email not found',
                an_email_with_a_link_has_been_sent_to_your_email: 'An email with a link has been sent to your email',
                find_by_vendor_code: 'Find by vendor code',
                colors: 'Colors',
                sizes: 'Sizes',
                contacts: 'Contacts',
                name: 'Name',
                no_results: 'No results',
                loading: 'Loading',
                phone_length_minimum_7_characters: 'Phone length minimum 7 characters',
                // your_order_may_take_some_time_to_process: 'Your order may take some time to process',
                sizes_table: 'Sizes table',
                load_more: 'Load more',
                out_of: 'out of',
                models: 'models',
                in_order_to_use_this_option_you_must_log_in_or_register:
                    'In order to use this option, you must log in or register.',
                you_need_to_login: 'You need to login!',
                sended: 'Sended',
                store_key: 'Store key',
                enter_store_key: 'Enter store key!',
                this_catalog_is_private_in_order_to_enter_you_must_enter_the_key:
                    'This catalog is private, in order to enter you must enter the key.',
                this_catalog_does_not_support_the_current_language_to_continue_select_a_language_from_the_list_in_the_languages_menu:
                    'This catalog does not support the current language, to continue, select a language from the list in the languages ​​menu',
                language_error: 'Language error!',
                spanish: 'Spain',
                french: 'French',
            },
        },
        {
            code: 'ua',
            string: {
                shown: 'Зображено',
                call_back_messageA:
                    'Привіт! Якщо у вас є запитання, коментарі або потрібна допомога, зв’яжіться з нами. Ми готові допомогти вам з вибором, надати додаткову інформацію про товар або допомогти оформити замовлення.',
                call_back_messageB: 'Ви можете зв’язатися з нами в будь-якому доступному месенджері або по телефону.',
                call_back_messageC: 'Дякуємо за інтерес до нашого онлайн-каталогу!',
                languages: 'Мови',
                back_to_stores: 'Повернутися до магазинiв',
                ok: 'Ок',
                search: 'Знайти',
                language: 'Мова',
                wrong_key: 'Неправильний ключ!',
                approve: 'Пiдтвердити',
                ready: 'Готово',
                clear_filters: 'Очистити фільтри',
                clear: 'Очистити',
                filters: 'Фільтри',
                nothing_was_found: 'Нічого не знайдено',
                stores: 'Магазини',
                catalog: 'Каталог',
                polish: 'Польська',
                czech: 'Чеська',
                russian: 'Російська',
                ukrainian: 'Українська',
                english: 'Англійська',
                find_store_by_name: 'Знайти магазин по назві',
                favorites: 'Уподобане',
                my_stores: 'Мої магазини',
                login: 'Вхід',
                register: 'Зареєструватися',
                wrong_login_or_password: 'Неправильний логін або пароль',
                forgot_password: 'Забули пароль?',
                cart: 'Кошик',
                vendor_code: 'Артикул',
                price: 'Ціна',
                logout: 'Вийти',
                submit: 'Підтвердити',
                ukraine: 'Україна',
                czechia: 'Чехія',
                italy: 'Італія',
                kazakhstan: 'Казахстан',
                poland: 'Польща',
                turkey: 'Туреччина',
                description: 'Опис',
                added: 'Додано',
                add_to: 'Додати до',
                // confirm_order: 'Підтвердити замовлення',
                // personal_data: 'Особисті дані',
                first_name: `Ім'я`,
                last_name: 'Прізвище',
                // receiver_first_name: `Ім'я одержувача`,
                // receiver_last_name: 'Прізвище одержувача',
                // receiver_phone_number: 'Номер телефону одержувача',
                phone_number: 'Номер телефону',
                city: 'Місто',
                email: 'Електронна пошта',
                password: 'Пароль',
                confirm_password: 'Підтвердити пароль',
                company_name: 'Назва компанії',
                already_registered: 'Вже зареєстровані',
                do_want_to_logout: 'Ви дійсно хочете залишити обліковий запис?',
                cancel: 'Скасувати',
                // confirm: 'Підтвердити',
                // do_you_want_to_confirm_order: 'Хочете підтвердити замовлення?',
                // order: 'Замовлення',
                clear_cart: 'Очистити кошик',
                do_you_want_to_clear_cart: 'Бажаєте очистити кошик?',
                // clear_favorites: 'Очистити уподобане',
                // do_you_want_to_clear_favorites: 'Бажаєте очистити уподобане?',
                // promo_code: 'Промокод',
                enter_password: 'Введіть пароль',
                enter_email: 'Введіть електронну пошту',
                enter_valid_email: 'Введіть дійсну електронну пошту',
                password_length_min_8_symbols: 'Довжина пароля не менше 8 символів',
                passwords_do_not_match: 'Паролі не збігаються',
                enter_first_name: `Введіть ім'я`,
                enter_last_name: 'Введіть прізвище',
                enter_phone_number: 'Введіть номер телефону',
                // login_to_order: 'Увійдіть, щоб замовити',
                // my_orders: 'Мої замовлення',
                my_profile: 'Профіль',
                // price_per_item: 'Ціна за шт.',
                country: 'Країна',
                e_a: 'од.',
                reset_password: 'Скинути пароль',

                close: 'Закрити',
                please_enter_your_email_address_you_will_receive_a_link_to_create_a_new_password_via_email:
                    'Будь ласка, введіть адресу електронної пошти. Ви отримаєте електронною поштою посилання для створення нового пароля.',
                an_email_with_a_link_has_been_sent_to_your_email:
                    'На Вашу електронну пошту надіслано листа з посиланням',
                user_with_this_email_not_found: 'Користувача з такою електронною поштою не знайдено',
                find_by_vendor_code: 'Знайти модель за артикулом',
                colors: 'Кольори',
                sizes: 'Розміри',
                contacts: 'Контакти',
                name: 'Назва',
                no_results: 'Немає результатів',
                loading: 'Завантаження',
                phone_length_minimum_7_characters: 'Довжина телефону не менше 7 символів',
                // your_order_may_take_some_time_to_process: 'Обробка вашого замовлення може зайняти деякий час.',
                sizes_table: 'Таблиця розмірів',
                // international: 'Міжнарод.',
                // chest_girth: 'Обхват грудей',
                // waist_circumference: 'Обхват талії',
                // hip_girth: 'Обхват стегон',
                load_more: 'Завантажити більше',
                out_of: 'з',
                models: 'моделей',
                in_order_to_use_this_option_you_must_log_in_or_register:
                    'Щоб скористатися цією опцією, ви повинні увійти або зареєструватися.',
                you_need_to_login: 'Потрібно увійти!',
                sended: 'Надіслано',
                store_key: 'Ключ магазину',
                enter_store_key: 'Введіть ключ магазину!',
                this_catalog_is_private_in_order_to_enter_you_must_enter_the_key:
                    'Цей каталог є приватним, щоб увійти необхідно ввести ключ каталогу.',
                this_catalog_does_not_support_the_current_language_to_continue_select_a_language_from_the_list_in_the_languages_menu:
                    'Цей каталог не підтримує поточну мову, щоб продовжити, виберіть мову зі списку в меню мов',
                language_error: 'Помилка мови!',
                spanish: 'Іспанська',
                french: 'Французька',
            },
        },
        {
            code: 'pl',
            string: {
                shown: 'Pokazano',
                call_back_messageA:
                    'Cześć! Jeśli masz pytania, uwagi lub potrzebujesz pomocy, skontaktuj się z nami. Chętnie pomożemy w dokonaniu wyboru, udzielimy dodatkowych informacji o produkcie lub pomożemy w złożeniu zamówienia.',
                call_back_messageB:
                    'Można się z nami skontaktować w dowolnym komunikatorze dostępnym lub telefonicznie.',
                call_back_messageC: 'Dziękujemy za zainteresowanie naszym katalogiem online!',
                languages: 'Języki',
                back_to_stores: 'Wróć do sklepów',
                ok: 'Ok',
                search: 'Szukaj',
                language: 'Język',
                wrong_key: 'Niewłaściwy klucz!',
                approve: 'Zatwierdzić',
                ready: 'Gotowy',
                clear_filters: 'Wyczyść filtry',
                clear: 'Wyczyść',
                filters: 'Filtry',
                nothing_was_found: 'Nic nie zostało znalezione',
                stores: 'Sklepy',
                catalog: 'Katalog',
                polish: 'Polski',
                czech: 'Czeski',
                russian: 'Rosyjski',
                ukrainian: 'Ukraiński',
                english: 'Angielski',
                find_store_by_name: 'Znajdź sklep według nazwy',
                favorites: 'Ulubione',
                my_stores: 'Moje sklepy',
                login: 'Zaloguj się',
                register: 'Zarejestruj się',
                wrong_login_or_password: 'Błędny login lub hasło',
                forgot_password: 'Zapomniałem hasła?',
                cart: 'Koszyk',
                vendor_code: 'Kod',
                price: 'Cena',
                logout: 'Wyloguj',
                submit: 'Składać',
                ukraine: 'Ukraina',
                czechia: 'Czechy',
                italy: 'Włochy',
                kazakhstan: 'Kazachstan',
                poland: 'Polska',
                turkey: 'Turcja', //
                description: 'Opis',
                added: 'Dodano',
                add_to: 'Dodaj do',
                // confirm_order: 'Potwierdź zamówienie',
                // personal_data: 'Dane osobowe',
                first_name: 'Imię',
                last_name: 'Nazwisko',
                // receiver_first_name: 'Imię odbiorcy',
                // receiver_last_name: 'Nazwisko odbiorcy',
                // receiver_phone_number: 'Numer telefonu odbiorcy',
                phone_number: 'Numer telefonu',
                city: 'Miasto',
                email: 'E-mail',
                password: 'Hasło',
                confirm_password: 'Potwierdź hasło',
                company_name: 'Nazwa firmy',
                already_registered: 'Już zarejestrowany',
                do_want_to_logout: 'Czy na pewno chcesz opuścić swoje konto?',
                // delivery_information: 'Informacje o dostawie',
                // additional_information: 'Dodatkowe informacje',
                // post_office: 'Urząd Pocztowy',
                // comments: 'Komentarze', //
                // status: 'Stan',
                // ordered_date: 'Data zamówienia', //
                // delete_item: 'Usuń element',
                // do_you_want_to_delete_item: 'Czy chcesz usunąć element?',
                cancel: 'Anuluj',
                // confirm: 'Potwierdź',
                // do_you_want_to_confirm_order: 'Czy chcesz potwierdzić zamówienie?',
                // order: 'Zamówienie',
                clear_cart: 'Wyczyść koszyk',
                do_you_want_to_clear_cart: 'Czy chcesz wyczyścić koszyk?',
                // clear_favorites: 'Wyczyść ulubione',
                // do_you_want_to_clear_favorites: 'Czy chcesz wyczyścić ulubione?',
                // promo_code: 'Kod promocyjny',
                enter_password: 'Wprowadź hasło',
                enter_email: 'Wpisz email',
                enter_valid_email: 'Wprowadź prawidłowy adres e-mail',
                password_length_min_8_symbols: 'Długość hasła min. 8 znaków',
                passwords_do_not_match: 'Hasła się nie zgadzają',
                enter_first_name: 'Wpisz imię',
                enter_last_name: 'Wpisz nazwisko',
                enter_phone_number: 'Wprowadź numer telefonu',
                // login_to_order: 'Zaloguj się, aby złożyć zamówienie',
                // my_orders: 'Moje zamówienia',
                my_profile: 'Mój profil',
                // price_per_item: 'Cena za sztukę',
                country: 'Kraj',
                e_a: 'e.a.',
                reset_password: 'Zresetuj hasło',
                close: 'Zamknij',
                please_enter_your_email_address_you_will_receive_a_link_to_create_a_new_password_via_email:
                    'Podaj swój adres e-mail. Otrzymasz wiadomość e-mail z linkiem do utworzenia nowego hasła.',
                user_with_this_email_not_found: 'Nie znaleziono użytkownika z tym adresem e-mail',
                an_email_with_a_link_has_been_sent_to_your_email:
                    'E-mail z linkiem został wysłany na Twój adres e-mail',
                find_by_vendor_code: 'Znajdź według kodu dostawcy',
                colors: 'Kolory',
                sizes: 'Rozmiary',
                contacts: 'Kontakty',
                name: 'Nazwa',
                no_results: 'Brak wyników',
                loading: 'Ładowanie',
                phone_length_minimum_7_characters: 'Długość telefonu minimum 7 znaków',
                // your_order_may_take_some_time_to_process: 'Przetwarzanie Twojego zamówienia może trochę potrwaćs',
                sizes_table: 'Tabela rozmiarów',
                // international: 'Międzynarodowy',
                // chest_girth: 'Obwód klatki piersiowej',
                // waist_circumference: 'Obwód talii',
                // hip_girth: 'Obwód bioder',
                load_more: 'Załaduj więcej',
                // promo: 'Promocja',
                // promo_options: 'Opcje promocji',
                // edit_promo: 'Edytuj promocję',
                // add_promo: 'Dodaj promocję',
                // available_promo: 'Dostępna promocja',
                // add_promo_code: 'Dodaj kod promocyjny',
                // promo_name: 'Nazwa promocji',
                // add_promo_name: 'Dodaj nazwę promocji',
                out_of: 'ze',
                models: 'modeli',
                in_order_to_use_this_option_you_must_log_in_or_register:
                    'Aby skorzystać z tej opcji należy się zalogować lub zarejestrować.',
                you_need_to_login: 'Musisz się zalogować!',
                sended: 'Wysłano',
                store_key: 'Klucz sklepu',
                enter_store_key: 'Wprowadź klucz sklepu',
                this_catalog_is_private_in_order_to_enter_you_must_enter_the_key:
                    'Ten katalog jest prywatny, aby do niego wejść, musisz wprowadzić klucz katalogu.',
                this_catalog_does_not_support_the_current_language_to_continue_select_a_language_from_the_list_in_the_languages_menu:
                    'Ten katalog nie obsługuje bieżącego języka, aby kontynuować, wybierz język z listy w menu języków',
                language_error: 'Błąd językowy!',
                spanish: 'Hiszpański',
                french: 'Francuski',
            },
        },
        {
            code: 'cz',
            string: {
                shown: 'Zobrazeno',
                call_back_messageA:
                    'Ahoj! Pokud máte dotazy, připomínky nebo potřebujete pomoc, kontaktujte nás. Jsme připraveni vám pomoci s výběrem, poskytnout doplňující informace o produktu nebo pomoci s objednávkou.',
                call_back_messageB: 'Můžete nás kontaktovat v jakémkoli uvedeném messengeru nebo telefonicky.',

                languages: 'Jazyky',
                back_to_stores: 'Vraťte se do obchodů',
                ok: 'Ok',
                search: 'Nalézt',
                language: 'Jazyk',
                wrong_key: 'Špatný klíč!',
                approve: 'Schvalovat',
                ready: 'Připraven',
                clear_filters: 'Vymazat filtry',
                clear: 'Vymazat',
                filters: 'Filtry',
                nothing_was_found: 'Nic nebylo nalezeno',
                stores: 'Obchody',
                catalog: 'Katalog',
                polish: 'Polština',
                czech: 'Ceština',
                russian: 'Ruština',
                ukrainian: 'Ukrajinský',
                english: 'Angličtina',
                find_store_by_name: 'Najděte obchod podle názvu',
                favorites: 'Oblíbené',
                my_stores: 'Moje obchody',
                login: 'Přihlásit',
                register: 'Registrovat',
                wrong_login_or_password: 'Chybné přihlašovací jméno nebo heslo',
                forgot_password: 'Zapomenuté heslo?',
                cart: 'Košík',
                vendor_code: 'Kód',
                // color: 'Barva',
                // available_sizes: 'Dostupné velikosti',
                // go_to_details: 'Přejít na podrobnosti',
                // remove: 'Odstranit',
                price: 'Cena',
                // total_price: 'Celková cena',
                // total_quantity: 'Celkové množství',
                // add_product_sizes: 'Přidat velikosti produktů',
                // gallery: 'Galerie',
                // admin: 'Admin',
                logout: 'Odhlásit',
                submit: 'Předložit',
                ukraine: 'Ukrajina',
                czechia: 'Czechia',
                italy: 'Itálie',
                kazakhstan: 'Kazachstán',
                poland: 'Polsko',
                turkey: 'Turecko',
                description: 'Popis',
                added: 'Přidáno',
                add_to: 'Přidat do',
                // confirm_order: 'Potvrdit objednávku',
                // personal_data: 'Osobní údaje',
                first_name: 'Křestní jméno',
                last_name: 'Příjmení',
                // receiver_first_name: 'Křestní jméno příjemce',
                // receiver_last_name: 'Příjmení příjemce',
                // receiver_phone_number: 'Telefonní číslo příjemce',
                phone_number: 'Telefonní číslo',
                city: 'Město',
                email: 'Email',
                password: 'Heslo',
                confirm_password: 'Potvrdit heslo',
                company_name: 'Název společnosti',
                already_registered: 'Již zaregistrován',
                do_want_to_logout: 'Opravdu chcete opustit svůj účet?',
                cancel: 'Cancel',
                // confirm: 'Potvrdit',
                // do_you_want_to_confirm_order: 'Chcete potvrdit objednávku?',
                // order: 'Objednat',
                clear_cart: 'Vymazat košík',
                do_you_want_to_clear_cart: 'Chcete vymazat košík?',
                // clear_favorites: 'Vymazat oblíbené',
                // do_you_want_to_clear_favorites: 'Chcete vymazat oblíbené položky?',
                // promo_code: 'Promo kód',
                enter_password: 'Zadejte heslo',
                enter_email: 'Zadejte e-mail',
                enter_valid_email: 'Zadejte platný e-mail',
                password_length_min_8_symbols: 'Délka hesla min 8 symbolů',
                passwords_do_not_match: 'Hesla se neshodují',
                enter_first_name: 'Zadejte křestní jméno',
                enter_last_name: 'Zadejte příjmení',
                enter_phone_number: 'Zadejte telefonní číslo',
                // login_to_order: 'Přihlášení k objednávce',
                // my_orders: 'Moje objednávky',
                my_profile: 'Můj profil',
                // price_per_item: 'Cena za položku',
                country: 'Země',
                e_a: 'e.a.',
                reset_password: 'Resetovat heslo',
                close: 'Zavřít',
                please_enter_your_email_address_you_will_receive_a_link_to_create_a_new_password_via_email:
                    'Prosím zadejte svou e-mailovou adresu. E-mailem obdržíte odkaz pro vytvoření nového hesla.',
                user_with_this_email_not_found: 'Uživatel s tímto e-mailem nebyl nalezen',
                an_email_with_a_link_has_been_sent_to_your_email: 'Na váš e-mail byl odeslán e-mail s odkazem',
                find_by_vendor_code: 'Najít podle kódu dodavatele',
                colors: 'Barvy',
                sizes: 'Velikosti',

                contacts: 'Kontakty',
                name: 'Jméno',
                no_results: 'Žádné výsledky',
                loading: 'Načítání',
                phone_length_minimum_7_characters: 'Minimální délka telefonu 7 znaků',
                // your_order_may_take_some_time_to_process: 'Zpracování vaší objednávky může nějakou dobu trvat',
                sizes_table: 'Tabulka velikostí',
                // international: 'International',
                // chest_girth: 'Obvod hrudníku',
                // waist_circumference: 'Obvod pasu',
                // hip_girth: 'Obvod boků',
                load_more: 'Načíst více',
                out_of: 'ze',
                models: 'modelů',
                in_order_to_use_this_option_you_must_log_in_or_register:
                    'Abyste mohli tuto možnost využít, musíte se přihlásit nebo zaregistrovat.',
                you_need_to_login: 'Musíte se přihlásit!',
                sended: 'Odesláno',
                store_key: 'Klíč obchodu',
                enter_store_key: 'Zadejte klíč obchodu!',
                this_catalog_is_private_in_order_to_enter_you_must_enter_the_key:
                    'Tento adresář je soukromý, pro vstup musíte zadat klíč adresáře.',
                this_catalog_does_not_support_the_current_language_to_continue_select_a_language_from_the_list_in_the_languages_menu:
                    'Tento katalog nepodporuje aktuální jazyk, pro pokračování vyberte jazyk ze seznamu v nabídce jazyků',
                language_error: 'Jazyková chyba!',
                spanish: 'Spanělština',
                french: 'Francouzština',
            },
        },
        {
            code: 'ru',
            string: {
                shown: 'Показано',
                call_back_messageA:
                    'Привет! Если у вас есть вопросы, комментарии или нужна помощь, пожалуйста, обратитесь к нам. Мы готовы помочь вам с выбором, предоставить вам дополнительную информацию о продукте или помочь с оформлением заказа.',
                call_back_messageB: 'Вы можете связаться с нами в любом доступном мессенджере или по телефону.',
                call_back_messageC: 'Спасибо за ваш интерес к нашему интернет-каталогу!',

                languages: 'Языки',
                back_to_stores: 'Вернуться к магазинам',
                ok: 'Ок',
                search: 'Поиск',
                language: 'Язык',
                wrong_key: 'Неверный ключ!',
                approve: 'Подтвердить',
                ready: 'Готово',
                clear_filters: 'Очистить филтры',
                clear: 'Очистить',
                filters: 'Фильтры',
                nothing_was_found: 'Ничего не найдено',
                stores: 'Магазины',
                catalog: 'Каталог',
                polish: 'Польский',
                czech: 'Чешский',
                russian: 'Русский',
                ukrainian: 'Украинский',
                english: 'Английский',
                find_store_by_name: 'Найти магазин по названию',
                favorites: 'Избранное',
                my_stores: 'Мои магазины',
                login: 'Вход',
                register: 'Регистрация',
                wrong_login_or_password: 'Неверный логин или пароль',
                forgot_password: 'Забыл пароль?',
                cart: 'Корзина',
                vendor_code: 'Артикул',
                price: 'Цена',
                logout: 'Выход',
                submit: 'Подтвердить',
                ukraine: 'Украина',
                czechia: 'Чехия',
                italy: 'Италия',
                kazakhstan: 'Казахстан',
                poland: 'Польша',
                turkey: 'Турция',
                description: 'Описание',
                added: 'Добавлено',
                add_to: 'Добавить в',
                // confirm_order: 'Подтвердить заказ',
                // personal_data: 'Персональные данные',
                first_name: 'Имя',
                last_name: 'Фамилия',
                // receiver_first_name: 'Имя получателя',
                // receiver_last_name: 'Фамилия получателя',
                // receiver_phone_number: 'Номер телефона получателя',
                phone_number: 'Номер телефона',
                city: 'Город',
                email: 'Email',
                password: 'Пароль',
                confirm_password: 'Подтвердить пароль',
                company_name: 'Имя компании',
                already_registered: 'Уже зарегестрирован',
                do_want_to_logout: 'Вы действительно хотите покинуть аккаунт?',
                cancel: 'Отмена',
                // confirm: 'Подтвердить',
                // do_you_want_to_confirm_order: 'Вы хотите подтвердить заказ?',
                // order: 'Заказ',
                clear_cart: 'Очистить корзину',
                do_you_want_to_clear_cart: 'Вы хотите очистить корзину?',
                // clear_favorites: 'Очистить избранное',
                // do_you_want_to_clear_favorites: 'Вы хотите очистить избранное?',
                // promo_code: 'Промо код',
                enter_password: 'Введите пароль',
                enter_email: 'Введите email',
                enter_valid_email: 'Введите корректный email',
                password_length_min_8_symbols: 'Пароль должен быть не менее 8 символов',
                passwords_do_not_match: 'Пароли не совпадают',
                enter_first_name: 'Введите имя',
                enter_last_name: 'Введите фамилию',
                enter_phone_number: 'Введите номер телефона',
                // login_to_order: 'Войти для заказа',
                // my_orders: 'Мои заказы',
                my_profile: 'Профиль',
                // price_per_item: 'Цена еденицы',
                country: 'Страна',
                e_a: 'ед.',
                reset_password: 'Сбросить пароль',
                close: 'Закрыть',
                please_enter_your_email_address_you_will_receive_a_link_to_create_a_new_password_via_email:
                    'Пожалуйста, введите Ваш адрес электронной почты. Вы получите ссылку для создания нового пароля по электронной почте.',
                user_with_this_email_not_found: 'Пользователь с этим адресом электронной почты не найден',
                an_email_with_a_link_has_been_sent_to_your_email:
                    'На ваш адрес электронной почты отправлено письмо со ссылкой',
                find_by_vendor_code: 'Найти по артикулу',
                colors: 'Цвета',
                sizes: 'Размеры',
                contacts: 'Контакты',
                name: 'Имя',
                no_results: 'Нет результатов',
                loading: 'Загрузка',
                phone_length_minimum_7_characters: 'минимум 7 символов',
                sizes_table: 'Таблица размеров',
                load_more: 'Загрузить еще',
                out_of: 'из',
                models: 'моделей',
                in_order_to_use_this_option_you_must_log_in_or_register:
                    'Для того, чтобы воспользоваться этой опцией, вам необходимо войти или зарегистрироваться.',
                you_need_to_login: 'Необходимо войти!',
                sended: 'Отправлено',
                store_key: 'Ключ магазина',
                enter_store_key: 'Введите ключ магазина!',
                this_catalog_is_private_in_order_to_enter_you_must_enter_the_key:
                    'Этот каталог приватный, для того чтобы войти вы должны ввести ключ.',
                this_catalog_does_not_support_the_current_language_to_continue_select_a_language_from_the_list_in_the_languages_menu:
                    'Этот каталог не поддерживает текущий язык, для продолжения выберите язык из списка в меню языков',
                language_error: 'Ошибка языка!',
                spanish: 'Испанский',
                french: 'Французкий',
            },
        },
    ];

    useEffect(() => {
        setCurrentLanguage(langList.find(({ code }) => code === lang));
    }, [lang]);

    return { currentLanguage };
};
