import { useEffect, useState } from 'react';

export const useGetLanguage = ({ lang }) => {
    const [currentLanguage, setCurrentLanguage] = useState({ code: '', string: {} });

    const langList = [
        {
            code: 'en',
            string: {
                home: 'Home',
                no_available_sizes: 'No available sizes',
                image_not_loaded: 'Image not loaded',
                no_categories_available: 'No categories available',
                back_to_shopping: 'Back To Shopping',
                order_sent_successfully: 'Order Sent Successfully',
                deleted_by_owner: 'Deleted By Owner',
                details: 'Details',
                final_price: 'Final Price',
                quantity: 'Quantity',
                size: 'Size',
                processed: 'Processed',
                ordered: 'Ordered',
                delivered: 'Delivered',
                refunded: 'Refunded',
                canceled: 'Canceled',
                order: 'Order',
                ordered_date: 'Order Date',
                personal_data: 'Personal Data',
                delivery_data: 'Delivery Data',
                update: 'Update',
                profile: 'Profile',
                orders: 'Orders',
                approve_favorites_clear: 'Approve favorites clear',
                clear_favorites: 'Clear favorites',
                approve_clear_cart: 'Approve clear cart',
                not_required: 'Not required',
                excluding_delivery: 'Excluding delivery',
                total: 'total',
                delivery_address: 'Delivery address',
                delivery_information: 'Delivery information',
                confirm_order: 'Confirm order',
                no_sizes_added: 'No sizes added',
                delete: 'Delete',
                select_sizes: 'Select Sizes',
                shown: 'Shown',
                call_back_messageA:
                    'Hello! If you have questions, comments or need assistance, please contact us. We are ready to help you with your choice, provide you with additional information about the product or help you place your order.',
                call_back_messageB: 'You can contact us in any messenger available or by phone.',
                call_back_messageC: 'Thank you for your interest in our online catalogue!',
                languages: 'Languages',
                back_to_stores: 'Back to stores',
                ok: 'Ok',
                search: 'Search',
                language: 'Language',
                wrong_key: 'Wrong key!',
                approve: 'Approve',
                ready: 'Ready',
                clear_filters: 'Clear filters',
                clear: 'Clear',
                filters: 'Filters',
                nothing_was_found: 'Nothing was found',
                stores: 'Stores',
                catalog: 'Catalog',
                polish: 'Polish',
                czech: 'Czech',
                russian: 'Russian',
                ukrainian: 'Ukrainian',
                english: 'English',
                find_store_by_name: 'Find store by name',
                favorites: 'Favorites',
                my_stores: 'My stores',
                login: 'Login',
                register: 'Register',
                wrong_login_or_password: 'Wrong login or password',
                forgot_password: 'Forgot password?',
                cart: 'Cart',
                vendor_code: 'Product code',
                price: 'Price',
                logout: 'Logout',
                submit: 'Submit',
                ukraine: 'Ukraine',
                czechia: 'Czechia',
                italy: 'Italy',
                kazakhstan: 'Kazakhstan',
                poland: 'Poland',
                turkey: 'Turkey',
                description: 'Description',
                added: 'Added',
                add_to: 'Add To',
                first_name: 'First Name',
                last_name: 'Last Name',
                phone_number: 'Phone Number',
                city: 'City',
                email: 'Email',
                password: 'Password',
                confirm_password: 'Confirm password',
                company_name: 'Company Name',
                already_registered: 'Already registered',
                do_want_to_logout: 'Are you sure you want to leave your account?',
                cancel: 'Cancel',
                clear_cart: 'Clear cart',
                do_you_want_to_clear_cart: 'Do you want to clear cart?',
                enter_password: 'Enter password',
                enter_email: 'Enter email',
                enter_valid_email: 'Enter valid email',
                password_length_min_8_symbols: 'Password length min 8 symbols',
                passwords_do_not_match: 'Passwords do not match',
                enter_first_name: 'Enter first name',
                enter_last_name: 'Enter last name',
                enter_phone_number: 'Enter phone number',
                my_profile: 'My profile',
                country: 'Country',
                e_a: 'e.a.',
                reset_password: 'Reset Password',
                close: 'Close',
                please_enter_your_email_address_you_will_receive_a_link_to_create_a_new_password_via_email:
                    'Please enter your email address. You will receive a link to create a new password via email.',
                user_with_this_email_not_found: 'User with this email not found',
                an_email_with_a_link_has_been_sent_to_your_email: 'An email with a link has been sent to your email',
                find_by_vendor_code: 'Find by product code',
                colors: 'Colors',
                color: 'Color',
                sizes: 'Sizes',
                contacts: 'Contacts',
                name: 'Name',
                no_results: 'No results',
                loading: 'Loading',
                phone_length_minimum_7_characters: 'Phone length minimum 7 characters',
                sizes_table: 'Sizes table',
                load_more: 'Load more',
                out_of: 'out of',
                models: 'models',
                in_order_to_use_this_option_you_must_log_in_or_register:
                    'In order to use this option, you must log in or register.',
                you_need_to_login: 'You need to login!',
                sended: 'Sended',
                store_key: 'Store key',
                enter_store_key: 'Enter store key!',
                this_catalog_is_private_in_order_to_enter_you_must_enter_the_key:
                    'This catalog is private, in order to enter you must enter the key.',
                this_catalog_does_not_support_the_current_language_to_continue_select_a_language_from_the_list_in_the_languages_menu:
                    'This catalog does not support the current language, to continue, select a language from the list in the languages ​​menu',
                language_error: 'Language error!',
                spanish: 'Spain',
                french: 'French',
            },
        },
        {
            code: 'fr',
            string: {
                home: 'Home',
                no_available_sizes: 'Aucune taille disponible',
                image_not_loaded: 'Image non chargée',
                no_categories_available: 'Aucune catégorie disponible',
                back_to_shopping: 'Retour aux achats',
                order_sent_successfully: 'Commande envoyée avec succès',
                deleted_by_owner: 'Supprimé par le propriétaire',
                details: 'Détails',
                final_price: 'Prix final',
                quantity: 'Quantité',
                size: 'Taille',
                processed: 'Traité',
                ordered: 'Commandé',
                delivered: 'Livré',
                refunded: 'Remboursé',
                canceled: 'Annulé',
                order: 'Commander',
                ordered_date: 'Date de commande',
                personal_data: 'Données personnelles',
                delivery_data: 'Données de livraison',
                update: 'Mise à jour',
                profile: 'Profil',
                orders: 'Commandes',
                approve_favorites_clear: 'Approuver la suppression des favoris',
                clear_favorites: 'Effacer les favoris',
                approve_clear_cart: 'Approuver l`effacement du panier',
                not_required: 'Non requis',
                excluding_delivery: 'Hors livraison',
                total: 'total',
                delivery_address: 'Adresse de livraison',
                delivery_information: 'Informations de livraison',
                confirm_order: 'Confirmer la commande',
                no_sizes_added: 'Aucune taille ajoutée',
                delete: 'Supprimer',
                select_sizes: 'Sélectionner les tailles',
                show: 'ShAffichéown',
                call_back_messageA:
                    'Bonjour! Si vous avez des questions, des commentaires ou avez besoin d`aide, veuillez nous contacter. Nous sommes prêts à vous aider dans votre choix, à vous fournir des informations complémentaires sur le produit ou à vous aider à passer votre commande.',

                call_back_messageB:
                    'Vous pouvez nous contacter dans n`importe quel messager disponible ou par téléphone.',
                call_back_messageC: 'Merci de l`intérêt que vous portez à notre catalogue en ligne!',
                languages: 'Langues',
                back_to_stores: 'Retour aux magasins',
                ok: 'Ok',
                search: 'Chercher',
                language: 'Langue',
                wrong_key: 'Mauvaise clé!',
                approve: 'Approuver',
                ready: 'Prêt',
                clear_filters: 'Effacer les filtres',
                clear: 'Effacer',
                filters: 'Filtres',
                nothing_was_found: 'Rien n1a été trouvé',
                stores: 'Magasins',
                catalog: 'Catalogue',
                polish: 'Polonais',
                czech: 'Tchèque',
                russian: 'Russe',
                ukrainian: 'Ukrainien',
                english: 'Anglais',
                find_store_by_name: 'Trouver un magasin par nom',
                favorites: 'Favoris',
                my_stores: 'Mes magasins',
                login: 'Connexion',
                register: 'S`inscrire',
                wrong_login_or_password: 'Connexion ou mot de passe incorrect',
                forgot_password: 'Mot de passe oublié?',
                cart: 'Panier',
                vendor_code: 'Code du fournisseur',
                price: 'Prix',
                logout: 'Déconnexion',
                submit: 'Soumettre',
                ukraine: 'Ukraine',
                czechia: 'Tchéquie',
                italy: 'Italie',
                kazakhstan: 'Kazakhstan',
                poland: 'Pologne',
                turkey: 'Turquie',
                description: 'Description',
                added: 'Ajouté',
                add_to: 'Ajouter à',
                first_name: 'Prénom',
                last_name: 'Nom de famille',
                phone_number: 'Numéro de téléphone',
                city: 'Ville',
                email: 'E-mail',
                password: 'Mot de passe',
                confirm_password: 'Confirmer le mot de passe',
                company_name: 'Nom de l`entreprise',
                already_registered: 'Déjà inscrit',
                do_want_to_logout: 'Etes-vous sûr de vouloir quitter votre compte?',
                cancel: 'Annuler',
                clear_cart: 'Effacer le panie',
                do_you_want_to_clear_cart: 'Voulez-vous vider le panier?',
                enter_password: 'Entrez le mot de passe',
                enter_email: 'Entrez l`e-mail',
                enter_valid_email: 'Entrez une adresse e-mail valide',
                password_length_min_8_symbols: 'Longueur du mot de passe min 8 symboles',
                passwords_do_not_match: 'Les mots de passe ne correspondent pas',
                enter_first_name: 'Entrez le prénom',
                enter_last_name: 'Entrez le nom de famille',
                enter_phone_number: 'Entrez le numéro de téléphone',
                my_profile: 'Mon profil',
                country: 'Pays',
                e_a: 'e.a.',
                reset_password: 'Réinitialiser le mot de passe',
                close: 'Fermer',
                please_enter_your_email_address_you_will_receive_a_link_to_create_a_new_password_via_email:
                    'Veuillez entrer votre adresse e-mail. Vous recevrez un lien pour créer un nouveau mot de passe par e-mail.',
                user_with_this_email_not_found: 'Utilisateur avec cet email introuvable',
                an_email_with_a_link_has_been_sent_to_your_email: 'Un email avec un lien a été envoyé à votre email',
                find_by_vendor_code: 'Rechercher par code fournisseur',
                colors: 'Couleurs',
                color: 'Couleur',
                sizes: 'Tailles',
                contacts: 'Contacts',
                name: 'Nom',
                no_results: 'Aucun résultat',
                loading: 'Chargement',
                phone_length_minimum_7_characters: 'Longueur du téléphone minimum 7 caractères',
                sizes_table: 'Tableau des tailles',
                load_more: 'Charger plus',
                out_of: 'hors de',
                models: 'modèles',
                in_order_to_use_this_option_you_must_log_in_or_register:
                    'Pour utiliser cette option, vous devez vous connecter ou vous inscrire.',
                you_need_to_login: 'Vous devez vous connecter!',
                sended: 'Envoyé',
                store_key: 'Clé du magasin',
                enter_store_key: 'Entrez la clé du magasin!',
                this_catalog_is_private_in_order_to_enter_you_must_enter_the_key:
                    'Ce catalogue ne supporte pas la langue actuelle, pour continuer, sélectionnez une langue dans la liste du menu langues',
                this_catalog_does_not_support_the_current_language_to_continue_select_a_language_from_the_list_in_the_languages_menu:
                    'This catalog does not support the current language, to continue, select a language from the list in the languages ​​menu',
                language_error: 'Erreur de langue !',
                spanish: 'Espagne',
                french: 'Français',
            },
        },
        {
            code: 'es',
            string: {
                home: 'Home',
                no_available_sizes: 'No hay tallas disponibles',
                image_not_loaded: 'Imagen no cargada',
                no_categories_available: 'No hay categorías disponibles',
                back_to_shopping: 'Volver a comprar',
                order_sent_successfully: 'Pedido enviado con éxito',
                deleted_by_owner: 'Eliminado por el propietario',
                details: 'Detalles',
                final_price: 'Precio final',
                quantity: 'Cantidad',
                size: 'Tamaño',
                processed: 'Procesado',
                ordered: 'Ordenado',
                delivered: 'Entregado',
                refunded: 'Reembolsado',
                canceled: 'Cancelado',
                order: 'Orden',
                ordered_date: 'Fecha de orden',
                personal_data: 'Datos personales',
                delivery_data: 'Datos de entrega',
                update: 'Actualizar',
                profile: 'Perfil',
                orders: 'Pedidos',
                approve_favorites_clear: 'Aprobar favoritos claros',
                clear_favorites: 'Borrar favoritos',
                approve_clear_cart: 'Aprobar borrar carrito',
                not_required: 'No requerido',
                excluding_delivery: 'Excluyendo entrega',
                total: 'total',
                delivery_address: 'Dirección de entrega',
                delivery_information: 'Información de entrega',
                confirm_order: 'Confirmar pedido',
                no_sizes_added: 'No se agregaron tamaños',
                delete: 'Eliminar',
                select_sizes: 'Seleccionar tamaños',
                show: 'Mostrado',
                call_back_messageA:
                    'Hola! Si tiene preguntas, comentarios o necesita ayuda, por favor contáctenos. Estamos listos para ayudarle con su elección, brindarle información adicional sobre el producto o ayudarlo a realizar su pedido.',
                call_back_messageB: 'Puedes contactarnos en cualquier messenger disponible o por teléfono.',
                call_back_messageC: 'Gracias por su interés en nuestro catálogo en línea!',
                languages: 'Idiomas',
                back_to_stores: 'Volver a las tiendas',
                ok: 'Ok',
                search: 'Buscar',
                language: 'Idioma',
                wrong_key: 'Clave incorrecta!',
                approve: 'Aprobar',
                ready: 'Listo',
                clear_filters: 'Borrar filtros',
                clear: 'Borrar',
                filters: 'Filtros',
                nothing_was_found: 'No se encontró nada',
                stores: 'Tiendas',
                catalog: 'Catálogo',
                polish: 'Polaco',
                czech: 'Checo',
                russian: 'Ruso',
                ukrainian: 'Ucraniano',
                english: 'Englés',
                find_store_by_name: 'Buscar tienda por nombre',
                favorites: 'Favoritos',
                my_stores: 'Mis tiendas',
                login: 'Iniciar sesión',
                register: 'Registrarse',
                wrong_login_or_password: 'Inicio de sesión o contraseña incorrectos',
                forgot_password: 'Olvidaste tu contraseña?',
                cart: 'Carrito',
                vendor_code: 'Código de proveedor',
                price: 'Precio',
                logout: 'Cerrar sesión',
                submit: 'Enviar',
                ukraine: 'Ucrania',
                czechia: 'Chequia',
                italy: 'Italia',
                kazakhstan: 'Kazajstán',
                poland: 'Polonia',
                turkey: 'Turquía',
                description: 'Descripción',
                added: 'Agregado',
                first_name: 'Nombre de pila',
                last_name: 'Apellido',
                phone_number: 'Número de teléfono',
                city: 'Ciudad',
                email: 'Correo electrónico',
                password: 'Contraseña',
                confirm_password: 'Confirmar contraseña',
                company_name: 'Nombre de empresa',
                already_registered: 'Ya registrado',
                do_want_to_logout: 'Estás seguro de que quieres salir de tu cuenta?',
                cancel: 'Cancelar',
                clear_cart: 'Borrar carrito',
                do_you_want_to_clear_cart: 'Quieres borrar el carrito?',
                enter_password: 'Ingresar contraseña',
                enter_email: 'Ingresar correo electrónico',
                enter_valid_email: 'Ingrese un correo electrónico válido',
                password_length_min_8_symbols: 'Longitud mínima de la contraseña 8 símbolos',
                passwords_do_not_match: 'Las contraseñas no coinciden',
                enter_first_name: 'Ingrese el nombre',
                enter_last_name: 'Ingrese el apellido',
                enter_phone_number: 'Ingrese el número de teléfono',
                my_profile: 'Mi perfil',
                country: 'País',
                e_a: 'e.a.',
                reset_password: 'Restablecer contraseña',
                close: 'Cerca',
                please_enter_your_email_address_you_will_receive_a_link_to_create_a_new_password_via_email:
                    'Por favor, introduzca su dirección de correo electrónico. Recibirás un enlace para crear una nueva contraseña por correo electrónico.',
                user_with_this_email_not_found: 'Usuario con este correo electrónico no encontrado',
                an_email_with_a_link_has_been_sent_to_your_email:
                    'Se ha enviado un correo electrónico con un enlace a su correo electrónico',
                find_by_vendor_code: 'Buscar por código de proveedor',
                colors: 'Colores',
                color: 'Color',
                sizes: 'Tamaños',
                contacts: 'Contactos',
                name: 'Nombre',
                no_results: 'Sin resultados',
                loading: 'Cargando',
                phone_length_minimum_7_characters: 'Longitud mínima del teléfono 7 caracteres',
                sizes_table: 'Tabla de tamaños',
                load_more: 'Cargar más',
                out_of: 'fuera de',
                models: 'modelos',
                in_order_to_use_this_option_you_must_log_in_or_register:
                    'Para utilizar esta opción, debe iniciar sesión o registrarse.',
                you_need_to_login: 'Necesitas iniciar sesión!',
                sended: 'Enviado',
                store_key: 'Guardar clave',
                enter_store_key: 'Ingrese la clave de la tienda!',
                this_catalog_is_private_in_order_to_enter_you_must_enter_the_key:
                    'Este catálogo es privado, para poder ingresar debes ingresar la clave.',
                this_catalog_does_not_support_the_current_language_to_continue_select_a_language_from_the_list_in_the_languages_menu:
                    'Este catálogo no soporta el idioma actual, para continuar, seleccione un idioma de la lista en el menú de idiomas',
                language_error: 'Error de idioma!',
                spanish: 'España',
                french: 'Francés',
            },
        },
        {
            code: 'ua',
            string: {
                home: 'Home',
                no_available_sizes: 'Немає доступних розмірів',
                image_not_loaded: 'Зображення не завантажено',
                no_categories_available: 'Немає доступних категорій',
                back_to_shopping: 'Назад до покупок',
                order_sent_successfully: 'Замовлення успішно відправлено',
                deleted_by_owner: 'Видалено власником',
                details: 'Подробиці',
                final_price: 'Остаточна ціна',
                quantity: 'Кількість',
                size: 'Розмiр',
                processed: 'Обробелено',
                ordered: 'Замовлено',
                delivered: 'Доставлено',
                refunded: 'Повернено',
                canceled: 'Скасовано',
                order: 'Замовлення',
                ordered_date: 'Дата замовлення',
                personal_data: 'Особисті дані',
                delivery_data: 'Дані доставки',
                update: 'Оновити',
                profile: 'Профіль',
                orders: 'Замовлення',
                approve_favorites_clear: 'Схвалити видалення вибраного',
                clear_favorites: 'Очистити вибране',
                approve_clear_cart: 'Підтвердьте, щоб очистити кошик',
                not_required: 'Не обов`язково',
                excluding_delivery: 'Без доставки',
                total: 'Всього',
                delivery_address: 'Адреса доставки',
                delivery_information: 'Дані доставки',
                confirm_order: 'Пiдтвердити замовлення',
                no_sizes_added: 'Розміри не додані',
                delete: 'Видалити',
                select_sizes: 'Виберіть розміри',
                shown: 'Зображено',
                call_back_messageA:
                    'Привіт! Якщо у вас є запитання, коментарі або потрібна допомога, зв’яжіться з нами. Ми готові допомогти вам з вибором, надати додаткову інформацію про товар або допомогти оформити замовлення.',
                call_back_messageB: 'Ви можете зв’язатися з нами в будь-якому доступному месенджері або по телефону.',
                call_back_messageC: 'Дякуємо за інтерес до нашого онлайн-каталогу!',
                languages: 'Мови',
                back_to_stores: 'Повернутися до магазинiв',
                ok: 'Ок',
                search: 'Знайти',
                language: 'Мова',
                wrong_key: 'Неправильний ключ!',
                approve: 'Пiдтвердити',
                ready: 'Готово',
                clear_filters: 'Очистити фільтри',
                clear: 'Очистити',
                filters: 'Фільтри',
                nothing_was_found: 'Нічого не знайдено',
                stores: 'Магазини',
                catalog: 'Каталог',
                polish: 'Польська',
                czech: 'Чеська',
                russian: 'Російська',
                ukrainian: 'Українська',
                english: 'Англійська',
                find_store_by_name: 'Знайти магазин по назві',
                favorites: 'Уподобане',
                my_stores: 'Мої магазини',
                login: 'Вхід',
                register: 'Зареєструватися',
                wrong_login_or_password: 'Неправильний логін або пароль',
                forgot_password: 'Забули пароль?',
                cart: 'Кошик',
                vendor_code: 'Артикул',
                price: 'Ціна',
                logout: 'Вийти',
                submit: 'Підтвердити',
                ukraine: 'Україна',
                czechia: 'Чехія',
                italy: 'Італія',
                kazakhstan: 'Казахстан',
                poland: 'Польща',
                turkey: 'Туреччина',
                description: 'Опис',
                added: 'Додано',
                add_to: 'Додати до',
                first_name: `Ім'я`,
                last_name: 'Прізвище',
                phone_number: 'Номер телефону',
                city: 'Місто',
                email: 'Електронна пошта',
                password: 'Пароль',
                confirm_password: 'Підтвердити пароль',
                company_name: 'Назва компанії',
                already_registered: 'Вже зареєстровані',
                do_want_to_logout: 'Ви дійсно хочете залишити обліковий запис?',
                cancel: 'Скасувати',
                clear_cart: 'Очистити кошик',
                do_you_want_to_clear_cart: 'Бажаєте очистити кошик?',
                enter_password: 'Введіть пароль',
                enter_email: 'Введіть електронну пошту',
                enter_valid_email: 'Введіть дійсну електронну пошту',
                password_length_min_8_symbols: 'Довжина пароля не менше 8 символів',
                passwords_do_not_match: 'Паролі не збігаються',
                enter_first_name: `Введіть ім'я`,
                enter_last_name: 'Введіть прізвище',
                enter_phone_number: 'Введіть номер телефону',
                my_profile: 'Профіль',
                country: 'Країна',
                e_a: 'од.',
                reset_password: 'Скинути пароль',
                close: 'Закрити',
                please_enter_your_email_address_you_will_receive_a_link_to_create_a_new_password_via_email:
                    'Будь ласка, введіть адресу електронної пошти. Ви отримаєте електронною поштою посилання для створення нового пароля.',
                an_email_with_a_link_has_been_sent_to_your_email:
                    'На Вашу електронну пошту надіслано листа з посиланням',
                user_with_this_email_not_found: 'Користувача з такою електронною поштою не знайдено',
                find_by_vendor_code: 'Знайти модель за артикулом',
                colors: 'Кольори',
                color: 'Колiр',
                sizes: 'Розміри',
                contacts: 'Контакти',
                name: 'Назва',
                no_results: 'Немає результатів',
                loading: 'Завантаження',
                phone_length_minimum_7_characters: 'Довжина телефону не менше 7 символів',
                sizes_table: 'Таблиця розмірів',
                load_more: 'Завантажити більше',
                out_of: 'з',
                models: 'моделей',
                in_order_to_use_this_option_you_must_log_in_or_register:
                    'Щоб скористатися цією опцією, ви повинні увійти або зареєструватися.',
                you_need_to_login: 'Потрібно увійти!',
                sended: 'Надіслано',
                store_key: 'Ключ магазину',
                enter_store_key: 'Введіть ключ магазину!',
                this_catalog_is_private_in_order_to_enter_you_must_enter_the_key:
                    'Цей каталог є приватним, щоб увійти необхідно ввести ключ каталогу.',
                this_catalog_does_not_support_the_current_language_to_continue_select_a_language_from_the_list_in_the_languages_menu:
                    'Цей каталог не підтримує поточну мову, щоб продовжити, виберіть мову зі списку в меню мов',
                language_error: 'Помилка мови!',
                spanish: 'Іспанська',
                french: 'Французька',
            },
        },
        {
            code: 'pl',
            string: {
                home: 'Home',
                no_available_sizes: 'Brak dostępnych rozmiarów',
                image_not_loaded: 'Obraz nie został załadowany',
                no_categories_available: 'Brak dostępnych kategorii',
                back_to_shopping: 'Powrót do zakupów',
                order_sent_successfully: 'Zamówienie zostało wysłane pomyślnie',
                deleted_by_owner: 'Usunięte przez właściciela',
                details: 'Detale',
                final_price: 'Cena ostateczna',
                quantity: 'Ilość',
                size: 'Rozmiar',
                processed: 'Przetworzone',
                ordered: 'Zamówiłem',
                delivered: 'Dostarczone',
                refunded: 'Zwrócony',
                canceled: 'Anulowane',
                order: 'Zamówienia',
                ordered_date: 'Data zamówienia',
                personal_data: 'Dane Osobowe',
                delivery_data: 'Dane dostawy',
                update: 'Aktualizacja',
                profile: 'Profil',
                orders: 'Zamówienia',
                approve_favorites_clear: 'Zatwierdź ulubione jasne',
                clear_favorites: 'Wyczyść ulubione',
                approve_clear_cart: 'Zatwierdź wyczyszczenie koszyka',
                not_required: 'Nie wymagane',
                excluding_delivery: 'Z wyłączeniem dostawy',
                total: 'Całkowity',
                delivery_address: 'Adres dostawy',
                delivery_information: 'Szczegóły dostawy',
                confirm_order: 'Potwierdzić zamówienie',
                no_sizes_added: 'Nie dodano żadnych rozmiarów',
                delete: 'Usuwać',
                select_sizes: 'Wybierz rozmiary',
                shown: 'Pokazano',
                call_back_messageA:
                    'Cześć! Jeśli masz pytania, uwagi lub potrzebujesz pomocy, skontaktuj się z nami. Chętnie pomożemy w dokonaniu wyboru, udzielimy dodatkowych informacji o produkcie lub pomożemy w złożeniu zamówienia.',
                call_back_messageB:
                    'Można się z nami skontaktować w dowolnym komunikatorze dostępnym lub telefonicznie.',
                call_back_messageC: 'Dziękujemy za zainteresowanie naszym katalogiem online!',
                languages: 'Języki',
                back_to_stores: 'Wróć do sklepów',
                ok: 'Ok',
                search: 'Szukaj',
                language: 'Język',
                wrong_key: 'Niewłaściwy klucz!',
                approve: 'Zatwierdzić',
                ready: 'Gotowy',
                clear_filters: 'Wyczyść filtry',
                clear: 'Wyczyść',
                filters: 'Filtry',
                nothing_was_found: 'Nic nie zostało znalezione',
                stores: 'Sklepy',
                catalog: 'Katalog',
                polish: 'Polski',
                czech: 'Czeski',
                russian: 'Rosyjski',
                ukrainian: 'Ukraiński',
                english: 'Angielski',
                find_store_by_name: 'Znajdź sklep według nazwy',
                favorites: 'Ulubione',
                my_stores: 'Moje sklepy',
                login: 'Zaloguj się',
                register: 'Zarejestruj się',
                wrong_login_or_password: 'Błędny login lub hasło',
                forgot_password: 'Zapomniałem hasła?',
                cart: 'Koszyk',
                vendor_code: 'Kod',
                price: 'Cena',
                logout: 'Wyloguj',
                submit: 'Składać',
                ukraine: 'Ukraina',
                czechia: 'Czechy',
                italy: 'Włochy',
                kazakhstan: 'Kazachstan',
                poland: 'Polska',
                turkey: 'Turcja',
                description: 'Opis',
                added: 'Dodano',
                add_to: 'Dodaj do',
                first_name: 'Imię',
                last_name: 'Nazwisko',
                phone_number: 'Numer telefonu',
                city: 'Miasto',
                email: 'E-mail',
                password: 'Hasło',
                confirm_password: 'Potwierdź hasło',
                company_name: 'Nazwa firmy',
                already_registered: 'Już zarejestrowany',
                do_want_to_logout: 'Czy na pewno chcesz opuścić swoje konto?',
                cancel: 'Anuluj',
                clear_cart: 'Wyczyść koszyk',
                do_you_want_to_clear_cart: 'Czy chcesz wyczyścić koszyk?',
                enter_password: 'Wprowadź hasło',
                enter_email: 'Wpisz email',
                enter_valid_email: 'Wprowadź prawidłowy adres e-mail',
                password_length_min_8_symbols: 'Długość hasła min. 8 znaków',
                passwords_do_not_match: 'Hasła się nie zgadzają',
                enter_first_name: 'Wpisz imię',
                enter_last_name: 'Wpisz nazwisko',
                enter_phone_number: 'Wprowadź numer telefonu',
                my_profile: 'Mój profil',
                country: 'Kraj',
                e_a: 'e.a.',
                reset_password: 'Zresetuj hasło',
                close: 'Zamknij',
                please_enter_your_email_address_you_will_receive_a_link_to_create_a_new_password_via_email:
                    'Podaj swój adres e-mail. Otrzymasz wiadomość e-mail z linkiem do utworzenia nowego hasła.',
                user_with_this_email_not_found: 'Nie znaleziono użytkownika z tym adresem e-mail',
                an_email_with_a_link_has_been_sent_to_your_email:
                    'E-mail z linkiem został wysłany na Twój adres e-mail',
                find_by_vendor_code: 'Znajdź według kodu dostawcy',
                colors: 'Kolory',
                color: 'Kolor',
                sizes: 'Rozmiary',
                contacts: 'Kontakty',
                name: 'Nazwa',
                no_results: 'Brak wyników',
                loading: 'Ładowanie',
                phone_length_minimum_7_characters: 'Długość telefonu minimum 7 znaków',
                sizes_table: 'Tabela rozmiarów',
                load_more: 'Załaduj więcej',
                out_of: 'ze',
                models: 'modeli',
                in_order_to_use_this_option_you_must_log_in_or_register:
                    'Aby skorzystać z tej opcji należy się zalogować lub zarejestrować.',
                you_need_to_login: 'Musisz się zalogować!',
                sended: 'Wysłano',
                store_key: 'Klucz sklepu',
                enter_store_key: 'Wprowadź klucz sklepu',
                this_catalog_is_private_in_order_to_enter_you_must_enter_the_key:
                    'Ten katalog jest prywatny, aby do niego wejść, musisz wprowadzić klucz katalogu.',
                this_catalog_does_not_support_the_current_language_to_continue_select_a_language_from_the_list_in_the_languages_menu:
                    'Ten katalog nie obsługuje bieżącego języka, aby kontynuować, wybierz język z listy w menu języków',
                language_error: 'Błąd językowy!',
                spanish: 'Hiszpański',
                french: 'Francuski',
            },
        },
        {
            code: 'cz',
            string: {
                home: 'Home',
                no_available_sizes: 'Žádné dostupné velikosti',
                image_not_loaded: 'Obrázek není načten',
                no_categories_available: 'Nejsou k dispozici žádné kategorie',
                back_to_shopping: 'Zpět na nákupy',
                order_sent_successfully: 'Objednávka byla úspěšně odeslána',
                deleted_by_owner: 'Smazáno vlastníkem',
                details: 'Podrobnosti',
                final_price: 'Konečná cena',
                quantity: 'Množství',
                size: 'Velikost',
                processed: 'Zpracováno',
                ordered: 'Objednáno',
                delivered: 'Doručeno',
                refunded: 'Refunded',
                canceled: 'Zrušeno',
                order: 'Objednávky',
                ordered_date: 'Datum objednávky',
                personal_data: 'Osobní údaje',
                delivery_data: 'Delivery Data',
                update: 'Aktualizace',
                profile: 'Profil',
                orders: 'Objednávky',
                approve_favorites_clear: 'Schválit oblíbené je jasné',
                clear_favorites: 'Vymazat oblíbené',
                approve_clear_cart: 'Schválit přehledný košík',
                not_required: 'Není požadováno',
                excluding_delivery: 'S výjimkou doručení',
                total: 'Celkový',
                delivery_address: 'Adres dostawy',
                delivery_information: 'Detaily objednávky',
                confirm_order: 'Potvrďte objednávku',
                no_sizes_added: 'Nebyly přidány žádné velikosti',
                delete: 'Vymazat',
                select_sizes: 'Vyberte velikosti',
                shown: 'Zobrazeno',
                call_back_messageA:
                    'Ahoj! Pokud máte dotazy, připomínky nebo potřebujete pomoc, kontaktujte nás. Jsme připraveni vám pomoci s výběrem, poskytnout doplňující informace o produktu nebo pomoci s objednávkou.',
                call_back_messageB: 'Můžete nás kontaktovat v jakémkoli uvedeném messengeru nebo telefonicky.',
                languages: 'Jazyky',
                back_to_stores: 'Vraťte se do obchodů',
                ok: 'Ok',
                search: 'Nalézt',
                language: 'Jazyk',
                wrong_key: 'Špatný klíč!',
                approve: 'Schvalovat',
                ready: 'Připraven',
                clear_filters: 'Vymazat filtry',
                clear: 'Vymazat',
                filters: 'Filtry',
                nothing_was_found: 'Nic nebylo nalezeno',
                stores: 'Obchody',
                catalog: 'Katalog',
                polish: 'Polština',
                czech: 'Ceština',
                russian: 'Ruština',
                ukrainian: 'Ukrajinský',
                english: 'Angličtina',
                find_store_by_name: 'Najděte obchod podle názvu',
                favorites: 'Oblíbené',
                my_stores: 'Moje obchody',
                login: 'Přihlásit',
                register: 'Registrovat',
                wrong_login_or_password: 'Chybné přihlašovací jméno nebo heslo',
                forgot_password: 'Zapomenuté heslo?',
                cart: 'Košík',
                vendor_code: 'Kód',
                price: 'Cena',
                logout: 'Odhlásit',
                submit: 'Předložit',
                ukraine: 'Ukrajina',
                czechia: 'Czechia',
                italy: 'Itálie',
                kazakhstan: 'Kazachstán',
                poland: 'Polsko',
                turkey: 'Turecko',
                description: 'Popis',
                added: 'Přidáno',
                add_to: 'Přidat do',
                first_name: 'Křestní jméno',
                last_name: 'Příjmení',
                phone_number: 'Telefonní číslo',
                city: 'Město',
                email: 'Email',
                password: 'Heslo',
                confirm_password: 'Potvrdit heslo',
                company_name: 'Název společnosti',
                already_registered: 'Již zaregistrován',
                do_want_to_logout: 'Opravdu chcete opustit svůj účet?',
                cancel: 'Cancel',
                clear_cart: 'Vymazat košík',
                do_you_want_to_clear_cart: 'Chcete vymazat košík?',
                enter_password: 'Zadejte heslo',
                enter_email: 'Zadejte e-mail',
                enter_valid_email: 'Zadejte platný e-mail',
                password_length_min_8_symbols: 'Délka hesla min 8 symbolů',
                passwords_do_not_match: 'Hesla se neshodují',
                enter_first_name: 'Zadejte křestní jméno',
                enter_last_name: 'Zadejte příjmení',
                enter_phone_number: 'Zadejte telefonní číslo',
                my_profile: 'Můj profil',
                country: 'Země',
                e_a: 'e.a.',
                reset_password: 'Resetovat heslo',
                close: 'Zavřít',
                please_enter_your_email_address_you_will_receive_a_link_to_create_a_new_password_via_email:
                    'Prosím zadejte svou e-mailovou adresu. E-mailem obdržíte odkaz pro vytvoření nového hesla.',
                user_with_this_email_not_found: 'Uživatel s tímto e-mailem nebyl nalezen',
                an_email_with_a_link_has_been_sent_to_your_email: 'Na váš e-mail byl odeslán e-mail s odkazem',
                find_by_vendor_code: 'Najít podle kódu dodavatele',
                colors: 'Barvy',
                color: 'Barva',
                sizes: 'Velikosti',
                contacts: 'Kontakty',
                name: 'Jméno',
                no_results: 'Žádné výsledky',
                loading: 'Načítání',
                phone_length_minimum_7_characters: 'Minimální délka telefonu 7 znaků',
                sizes_table: 'Tabulka velikostí',
                load_more: 'Načíst více',
                out_of: 'ze',
                models: 'modelů',
                in_order_to_use_this_option_you_must_log_in_or_register:
                    'Abyste mohli tuto možnost využít, musíte se přihlásit nebo zaregistrovat.',
                you_need_to_login: 'Musíte se přihlásit!',
                sended: 'Odesláno',
                store_key: 'Klíč obchodu',
                enter_store_key: 'Zadejte klíč obchodu!',
                this_catalog_is_private_in_order_to_enter_you_must_enter_the_key:
                    'Tento adresář je soukromý, pro vstup musíte zadat klíč adresáře.',
                this_catalog_does_not_support_the_current_language_to_continue_select_a_language_from_the_list_in_the_languages_menu:
                    'Tento katalog nepodporuje aktuální jazyk, pro pokračování vyberte jazyk ze seznamu v nabídce jazyků',
                language_error: 'Jazyková chyba!',
                spanish: 'Spanělština',
                french: 'Francouzština',
            },
        },
        {
            code: 'ru',
            string: {
                home: 'Головна',
                no_available_sizes: 'Нет доступных размеров',
                image_not_loaded: 'Изображение не загружено',
                no_categories_available: 'Нет доступных категорий',
                back_to_shopping: 'Вернуться к покупкам',
                order_sent_successfully: 'Заказ успешно отправлен',
                deleted_by_owner: 'Удален владельцем',
                details: 'Детально',
                final_price: 'Итоговая Цена',
                quantity: 'Количество',
                size: 'Размер',
                processed: 'Обработано',
                ordered: 'Заказано',
                delivered: 'Доставлено',
                refunded: 'Возвратено',
                canceled: 'Отменено',
                order: 'Заказ',
                ordered_date: 'Дата Заказа',
                personal_data: 'Личные данные',
                delivery_data: 'Данные о доставке',
                update: 'Обновить',
                profile: 'Профиль',
                orders: 'Заказы',
                approve_favorites_clear: 'Одобрить очистить избранно',
                clear_favorites: 'Очистить избранное',
                approve_clear_cart: 'Одобрить очистку корзины',
                not_required: 'Не обязательно',
                excluding_delivery: 'Без доставки',
                total: 'Итого',
                delivery_address: 'Адресс доставки',
                delivery_information: 'Данные доставки',
                confirm_order: 'Подтвердить заказ',
                no_sizes_added: 'Размеры не добавлены',
                delete: 'Удалить',
                select_sizes: 'Выбереите размеры',
                shown: 'Показано',
                call_back_messageA:
                    'Привет! Если у вас есть вопросы, комментарии или нужна помощь, пожалуйста, обратитесь к нам. Мы готовы помочь вам с выбором, предоставить вам дополнительную информацию о продукте или помочь с оформлением заказа.',
                call_back_messageB: 'Вы можете связаться с нами в любом доступном мессенджере или по телефону.',
                call_back_messageC: 'Спасибо за ваш интерес к нашему интернет-каталогу!',

                languages: 'Языки',
                back_to_stores: 'Вернуться к магазинам',
                ok: 'Ок',
                search: 'Поиск',
                language: 'Язык',
                wrong_key: 'Неверный ключ!',
                approve: 'Подтвердить',
                ready: 'Готово',
                clear_filters: 'Очистить филтры',
                clear: 'Очистить',
                filters: 'Фильтры',
                nothing_was_found: 'Ничего не найдено',
                stores: 'Магазины',
                catalog: 'Каталог',
                polish: 'Польский',
                czech: 'Чешский',
                russian: 'Русский',
                ukrainian: 'Украинский',
                english: 'Английский',
                find_store_by_name: 'Найти магазин по названию',
                favorites: 'Избранное',
                my_stores: 'Мои магазины',
                login: 'Вход',
                register: 'Регистрация',
                wrong_login_or_password: 'Неверный логин или пароль',
                forgot_password: 'Забыл пароль?',
                cart: 'Корзина',
                vendor_code: 'Артикул',
                price: 'Цена',
                logout: 'Выход',
                submit: 'Подтвердить',
                ukraine: 'Украина',
                czechia: 'Чехия',
                italy: 'Италия',
                kazakhstan: 'Казахстан',
                poland: 'Польша',
                turkey: 'Турция',
                description: 'Описание',
                added: 'Добавлено',
                add_to: 'Добавить в',
                first_name: 'Имя',
                last_name: 'Фамилия',
                phone_number: 'Номер телефона',
                city: 'Город',
                email: 'Email',
                password: 'Пароль',
                confirm_password: 'Подтвердить пароль',
                company_name: 'Имя компании',
                already_registered: 'Уже зарегестрирован',
                do_want_to_logout: 'Вы действительно хотите покинуть аккаунт?',
                cancel: 'Отмена',
                clear_cart: 'Очистить корзину',
                do_you_want_to_clear_cart: 'Вы хотите очистить корзину?',
                enter_password: 'Введите пароль',
                enter_email: 'Введите email',
                enter_valid_email: 'Введите корректный email',
                password_length_min_8_symbols: 'Пароль должен быть не менее 8 символов',
                passwords_do_not_match: 'Пароли не совпадают',
                enter_first_name: 'Введите имя',
                enter_last_name: 'Введите фамилию',
                enter_phone_number: 'Введите номер телефона',
                my_profile: 'Профиль',
                country: 'Страна',
                e_a: 'ед.',
                reset_password: 'Сбросить пароль',
                close: 'Закрыть',
                please_enter_your_email_address_you_will_receive_a_link_to_create_a_new_password_via_email:
                    'Пожалуйста, введите Ваш адрес электронной почты. Вы получите ссылку для создания нового пароля по электронной почте.',
                user_with_this_email_not_found: 'Пользователь с этим адресом электронной почты не найден',
                an_email_with_a_link_has_been_sent_to_your_email:
                    'На ваш адрес электронной почты отправлено письмо со ссылкой',
                find_by_vendor_code: 'Найти по артикулу',
                colors: 'Цвета',
                color: 'Цвет',
                sizes: 'Размеры',
                contacts: 'Контакты',
                name: 'Имя',
                no_results: 'Нет результатов',
                loading: 'Загрузка',
                phone_length_minimum_7_characters: 'минимум 7 символов',
                sizes_table: 'Таблица размеров',
                load_more: 'Загрузить еще',
                out_of: 'из',
                models: 'моделей',
                in_order_to_use_this_option_you_must_log_in_or_register:
                    'Для того, чтобы воспользоваться этой опцией, вам необходимо войти или зарегистрироваться.',
                you_need_to_login: 'Необходимо войти!',
                sended: 'Отправлено',
                store_key: 'Ключ магазина',
                enter_store_key: 'Введите ключ магазина!',
                this_catalog_is_private_in_order_to_enter_you_must_enter_the_key:
                    'Этот каталог приватный, для того чтобы войти вы должны ввести ключ.',
                this_catalog_does_not_support_the_current_language_to_continue_select_a_language_from_the_list_in_the_languages_menu:
                    'Этот каталог не поддерживает текущий язык, для продолжения выберите язык из списка в меню языков',
                language_error: 'Ошибка языка!',
                spanish: 'Испанский',
                french: 'Французкий',
            },
        },
    ];

    useEffect(() => {
        setCurrentLanguage(langList.find(({ code }) => code === lang)); // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [lang]);

    return { currentLanguage };
};
