import { useEffect, useState } from 'react';

export const useGetLanguage = ({ lang }) => {
    const [currentLanguage, setCurrentLanguage] = useState({ code: '', string: {} });

    const langList = [
        {
            code: 'en',
            string: {
                languages: 'Languages',
                back_to_stores: 'Back to stores',
                ok: 'Ok',
                search: 'Search',
                language: 'language',
                wrong_key: 'Wrong key!',
                approve: 'Approve',
                ready: 'Ready',
                clear_filters: 'Clear filters',
                clear: 'Clear',
                filters: 'Filters',
                nothing_was_found: 'Nothing was found',
                stores: 'Stores',
                catalog: 'Catalog',
                polish: 'Polish',
                czech: 'Czech',
                russian: 'Russian',
                ukrainian: 'Ukrainian',
                english: 'English',
                find_store_by_name: 'Find store by name',
                favorites: 'Favorites',
                my_stores: 'My stores',
                login: 'Login',
                register: 'Register',
                wrong_login_or_password: 'Wrong login or password',
                forgot_password: 'Forgot password?',
                cart: 'Cart',
                vendor_code: 'Vendor code',
                // color: 'Color',
                // available_sizes: 'Available sizes',
                // go_to_details: 'Go to details',
                // remove: 'Remove',
                price: 'Price',
                // total_price: 'Total price',
                // total_quantity: 'Total quantity',
                // add_product_sizes: 'Add Product Sizes',
                // gallery: 'Gallery',
                // admin: 'Admin',
                logout: 'Logout',
                submit: 'Submit',
                ukraine: 'Ukraine',
                czechia: 'Czechia',
                italy: 'Italy',
                kazakhstan: 'Kazakhstan',
                poland: 'Poland',
                turkey: 'Turkey',
                description: 'Description',
                added: 'Added',
                add_to: 'Add To',
                // confirm_order: 'Confirm Order',
                // personal_data: 'Personal Data',
                first_name: 'First Name',
                last_name: 'Last Name',
                // receiver_first_name: 'Receiver First Name',
                // receiver_last_name: 'Receiver Last Name',
                // receiver_phone_number: 'Receiver Phone Number',
                phone_number: 'Phone Number',
                city: 'City',
                email: 'Email',
                password: 'Password',
                confirm_password: 'Confirm password',
                company_name: 'Company Name',
                already_registered: 'Already registered',
                do_want_to_logout: 'Are you sure you want to leave your account?',
                // delivery_information: 'Delivery Information',
                // additional_information: 'Additional Information',
                // post_office: 'Post Office',
                // comments: 'Comments',
                // status: 'Status',
                // ordered_date: 'Ordered Date',
                // delete_item: 'Delete Item',
                // do_you_want_to_delete_item: 'Do you want to delete item?',
                cancel: 'Cancel',
                // confirm: 'Confirm',
                // do_you_want_to_confirm_order: 'Do you want to confirm order?',
                // order: 'Order',
                clear_cart: 'Clear cart',
                do_you_want_to_clear_cart: 'Do you want to clear cart?',
                // clear_favorites: 'Clear favorites',
                // do_you_want_to_clear_favorites: 'Do you want to clear favorites?',
                // promo_code: 'Promo Code',
                enter_password: 'Enter password',
                enter_email: 'Enter email',
                enter_valid_email: 'Enter valid email',
                password_length_min_8_symbols: 'Password length min 8 symbols',
                passwords_do_not_match: 'Passwords do not match',
                enter_first_name: 'Enter first name',
                enter_last_name: 'Enter last name',
                enter_phone_number: 'Enter phone number',
                // login_to_order: 'Login to order',
                // my_orders: 'My orders',
                my_profile: 'My profile',
                // price_per_item: 'Price per item',
                country: 'Country',
                e_a: 'e.a.',
                reset_password: 'Reset Password',
                close: 'Close',
                please_enter_your_email_address_you_will_receive_a_link_to_create_a_new_password_via_email:
                    'Please enter your email address. You will receive a link to create a new password via email.',
                user_with_this_email_not_found: 'User with this email not found',
                an_email_with_a_link_has_been_sent_to_your_email: 'An email with a link has been sent to your email',
                find_by_vendor_code: 'Find by vendor code',
                // //ADMIN
                // orders_list: 'Order List',
                // customers_list: 'Customers List',
                // products_list: 'Products List',
                // products_QR_list: 'Products QR List',
                // products_options: 'Products Options',
                // add_user: 'Add User',
                // dashboard: 'Dashboard',
                // categories: 'Categories',
                colors: 'Colors',
                sizes: 'Sizes',
                // variants: 'Variants',
                // id: 'ID',
                // full_name: 'Full Name',
                // actions: 'Actions',
                // size: 'Size',
                // quantity: 'Quantity',
                // save: 'Save',
                // pledge: 'Pledge',
                contacts: 'Contacts',
                name: 'Name',
                // completeness: 'Completeness',
                // add_models: 'Add models',
                // add_images: 'Add images',
                // add_sizes: 'Add sizes',
                // completed: 'Completed',
                // available: 'Available',
                // create_new: 'Create New',
                // product_data: 'Product Data',
                // update: 'Update',
                // order_priority: 'Order priority',
                // models: 'Models',
                // add_product_to_add_sizes: 'Add Product To Add Sizes',
                // add_product_to_add_categories: 'Add Product To Add Categories',
                // add_product_to_add_models: ' Add Product To Add Models',
                // vendor_code_must_be_unique: 'Vendor code must be unique',
                // add: 'Add',
                // delete: 'Delete',
                // categories_options: 'Categories options',
                // new_category_name: 'New category name',
                // new_category_code: 'New category code',
                // selected_category: 'Selected Category',
                // add_category_name: 'Add category name',
                // root: 'Root',
                // add_category_code: 'Add category code',
                // colors_options: 'Colors options',
                // add_color: 'Add color',
                // edit_color: 'Edit color',
                // add_color_name: 'Add color name',
                // option_name: 'Option name',
                // color_code: 'Color code',
                // color_name: 'Color name',
                // available_colors: 'Available colors',
                // label: 'Label',
                // code: 'Code',
                // sizes_options: 'Sizes options',
                // edit_size: 'Edit size',
                // add_size: 'Add size',
                // size_code: 'Size code',
                // size_name: 'Size name',
                // add_size_code: 'Add size code',
                // add_size_name: 'Add size name',
                // variants_options: 'Variants options',
                // add_variant_by_color: 'Add variant by color',
                // available_variant: 'Available variants',
                // option_code: 'Option code',
                // add_option_code: 'Add option code',
                // option_value: 'Option value',
                // change_password: 'Change password',
                // new_password: 'New password',
                // product_create: 'Product create',
                // details: 'Details',
                // change_status: 'Change status',
                // do_you_want_to_change_order_status: 'Do you want to change order status?',
                // leave_the_comment: 'Leave the comment',
                // order_history: 'Order history',
                // products: 'Products',
                // //order status
                // processed: 'Processed',
                // ordered: 'Ordered',
                // delivered: 'Delivered',
                // refunded: 'Refunded',
                // canceled: 'Canceled',
                no_results: 'No results',
                loading: 'Loading',
                phone_length_minimum_7_characters: 'Phone length minimum 7 characters',
                // your_order_may_take_some_time_to_process: 'Your order may take some time to process',
                sizes_table: 'Sizes table',
                // international: 'International',
                // chest_girth: 'Chest girth',
                // waist_circumference: 'Waist circumference',
                // hip_girth: 'Hip girth',
                load_more: 'Load more',
                // promo: 'Promo',
                // promo_options: 'Promo options',
                // edit_promo: 'Edit promo',
                // add_promo: 'Add promo',
                // available_promo: 'Available promo',
                // add_promo_code: 'Add promo code',
                // promo_name: 'Promo name',
                // add_promo_name: 'Add promo name',
                out_of: 'out of',
                models: 'models',
                in_order_to_use_this_option_you_must_log_in_or_register:
                    'In order to use this option, you must log in or register.',
                you_need_to_login: 'You need to login!',
                sended: 'Sended',
                store_key: 'Store key',
                enter_store_key: 'Enter store key!',
                this_catalog_is_private_in_order_to_enter_you_must_enter_the_key:
                    'This catalog is private, in order to enter you must enter the key.',
                this_catalog_does_not_support_the_current_language_to_continue_select_a_language_from_the_list_in_the_languages_menu:
                    'This catalog does not support the current language, to continue, select a language from the list in the languages ​​menu',
                language_error: 'Language error!',
            },
        },
        {
            code: 'ua',
            string: {
                languages: 'Мови',
                back_to_stores: 'Повернутися до магазинiв',
                ok: 'Ок',
                search: 'Знайти',
                language: 'Мова',
                wrong_key: 'Неправильний ключ!',
                approve: 'Пiдтвердити',
                ready: 'Готово',
                clear_filters: 'Очистити фільтри',
                clear: 'Очистити',
                filters: 'Фільтри',
                nothing_was_found: 'Нічого не знайдено',
                stores: 'Магазини',
                catalog: 'Каталог',
                polish: 'Польська',
                czech: 'Чеська',
                russian: 'Російська',
                ukrainian: 'Українська',
                english: 'Англійська',
                find_store_by_name: 'Знайти магазин по назві',
                favorites: 'Уподобане',
                my_stores: 'Мої магазини',
                login: 'Вхід',
                register: 'Зареєструватися',
                wrong_login_or_password: 'Неправильний логін або пароль',
                forgot_password: 'Забули пароль?',
                cart: 'Кошик',
                vendor_code: 'Артикул',
                // color: 'Колір',
                // available_sizes: 'Доступні розміри',
                // go_to_details: 'Перейти до деталей',
                // remove: 'Видалити',
                price: 'Ціна',
                // total_price: 'Загальна сума',
                // total_quantity: 'Загальна кількість',
                // add_product_sizes: 'Додайте розміри продукту',
                // gallery: 'Галерея',
                // admin: 'Адмін',
                logout: 'Вийти',
                submit: 'Підтвердити',
                ukraine: 'Україна',
                czechia: 'Чехія',
                italy: 'Італія',
                kazakhstan: 'Казахстан',
                poland: 'Польща',
                turkey: 'Туреччина',
                description: 'Опис',
                added: 'Додано',
                add_to: 'Додати до',
                // confirm_order: 'Підтвердити замовлення',
                // personal_data: 'Особисті дані',
                first_name: `Ім'я`,
                last_name: 'Прізвище',
                // receiver_first_name: `Ім'я одержувача`,
                // receiver_last_name: 'Прізвище одержувача',
                // receiver_phone_number: 'Номер телефону одержувача',
                phone_number: 'Номер телефону',
                city: 'Місто',
                email: 'Електронна пошта',
                password: 'Пароль',
                confirm_password: 'Підтвердити пароль',
                company_name: 'Назва компанії',
                already_registered: 'Вже зареєстровані',
                do_want_to_logout: 'Ви дійсно хочете залишити обліковий запис?',
                // delivery_information: 'Інформація про доставку',
                // additional_information: 'Додаткова інформація',
                // post_office: 'Адреса поштового відділення',
                // comments: 'Коментарі',
                // status: 'Статус',
                // ordered_date: 'Дата замовлення',
                // delete_item: 'Видалити замовлення',
                // do_you_want_to_delete_item: 'Хочете видалити замовлення?',
                cancel: 'Скасувати',
                // confirm: 'Підтвердити',
                // do_you_want_to_confirm_order: 'Хочете підтвердити замовлення?',
                // order: 'Замовлення',
                clear_cart: 'Очистити кошик',
                do_you_want_to_clear_cart: 'Бажаєте очистити кошик?',
                // clear_favorites: 'Очистити уподобане',
                // do_you_want_to_clear_favorites: 'Бажаєте очистити уподобане?',
                // promo_code: 'Промокод',
                enter_password: 'Введіть пароль',
                enter_email: 'Введіть електронну пошту',
                enter_valid_email: 'Введіть дійсну електронну пошту',
                password_length_min_8_symbols: 'Довжина пароля не менше 8 символів',
                passwords_do_not_match: 'Паролі не збігаються',
                enter_first_name: `Введіть ім'я`,
                enter_last_name: 'Введіть прізвище',
                enter_phone_number: 'Введіть номер телефону',
                // login_to_order: 'Увійдіть, щоб замовити',
                // my_orders: 'Мої замовлення',
                my_profile: 'Профіль',
                // price_per_item: 'Ціна за шт.',
                country: 'Країна',
                e_a: 'од.',
                reset_password: 'Скинути пароль',

                close: 'Закрити',
                please_enter_your_email_address_you_will_receive_a_link_to_create_a_new_password_via_email:
                    'Будь ласка, введіть адресу електронної пошти. Ви отримаєте електронною поштою посилання для створення нового пароля.',
                an_email_with_a_link_has_been_sent_to_your_email:
                    'На Вашу електронну пошту надіслано листа з посиланням',
                user_with_this_email_not_found: 'Користувача з такою електронною поштою не знайдено',
                find_by_vendor_code: 'Знайти модель за артикулом',

                // //ADMIN
                // orders_list: 'Список замовлень',
                // customers_list: 'Список клієнтів',
                // products_list: 'Список Товару',
                // products_QR_list: 'Список QR Товару',
                // products_options: 'Опції продуктів',
                // add_user: 'Додати користувача',
                // dashboard: 'Аналітика',
                // categories: 'Категорії',
                colors: 'Кольори',
                sizes: 'Розміри',
                // variants: 'Класифікації',
                // id: '№',
                // full_name: `Повне ім'я`,
                // actions: 'Дії',
                // size: 'Розмір',
                // quantity: 'Кількість',
                // save: 'Зберегти',
                // pledge: 'Застава',
                contacts: 'Контакти',
                name: 'Назва',
                // completeness: 'Повнота',
                // add_models: 'Додати моделі',
                // add_images: 'Додайте зображення',
                // add_sizes: 'Додайте розміри',
                // completed: 'Виконано',
                // available: 'В наявності',
                // create_new: 'Створити новий',
                // product_data: 'Дані продукту',
                // update: 'Оновити',
                // order_priority: 'Пріоритет',
                // models: 'Моделі',
                // add: 'Додати',
                // add_product_to_add_sizes: 'Додати дані продукту для додавання розмірів',
                // add_product_to_add_categories: 'Додайте дані продукту, щоб додати категорії',
                // add_product_to_add_models: 'Додайте дані продукту, щоб додати моделі',
                // vendor_code_must_be_unique: 'Артикул має бути унікальним',
                // delete: 'Видалити',
                // categories_options: 'Параметри категорій',
                // new_category_name: 'Назва категорії',
                // new_category_code: 'Код категорії',
                // selected_category: 'Вибрана категорія',
                // add_category_name: 'Додайте назву категорії',
                // root: 'Корінь',
                // add_category_code: 'Додайте код категорії',
                // colors_options: 'Варіанти кольорів',
                // add_color: 'Додати колір',
                // edit_color: 'Редагувати колір',
                // add_color_name: 'Додайте назву кольору',
                // option_name: 'Назва опції',
                // color_code: 'Код кольору',
                // color_name: 'Назва кольору',
                // available_colors: 'Доступні кольори',
                // label: 'Позначка',
                // code: 'Код',
                // sizes_options: 'Варіанти розмірів',
                // edit_size: 'Редагувати розмір',
                // add_size: 'Додайте розмір',
                // size_code: 'Код розміру',
                // size_name: 'Назва розміру',
                // add_size_code: 'Додайте код розміру',
                // add_size_name: 'Додайте назву розміру',
                // variants_options: 'Варіанти класифікацій',
                // add_variant_by_color: 'Додати класифікацію за кольором',
                // available_variants: 'Доступні класифікації',
                // option_code: 'Код опції',
                // add_option_code: 'Додайте код опції',
                // option_value: 'Значення опції',
                // change_password: 'Змінити пароль',
                // new_password: 'Новий пароль',
                // product_create: 'Створення продукту',
                // details: 'Деталі',
                // change_status: 'Змінити статус',
                // do_you_want_to_change_order_status: 'Бажаєте змінити статус замовлення?',
                // leave_the_comment: 'Залишити коментар',
                // order_history: 'Історія Замовлення',
                // products: 'Товар',
                // //order status
                // processed: 'Зроблений',
                // ordered: 'Замовлений',
                // delivered: 'Доставлено',
                // refunded: 'Повернено',
                // canceled: 'Скасовано',
                no_results: 'Немає результатів',
                loading: 'Завантаження',
                phone_length_minimum_7_characters: 'Довжина телефону не менше 7 символів',
                // your_order_may_take_some_time_to_process: 'Обробка вашого замовлення може зайняти деякий час.',
                sizes_table: 'Таблиця розмірів',
                // international: 'Міжнарод.',
                // chest_girth: 'Обхват грудей',
                // waist_circumference: 'Обхват талії',
                // hip_girth: 'Обхват стегон',
                load_more: 'Завантажити більше моделей',
                // promo: 'Промо',
                // promo_options: 'Промо опції',
                // edit_promo: 'Редагувати промо',
                // add_promo: 'Додати промо',
                // available_promo: 'Доступні промо',
                // add_promo_code: 'Додати промо код',
                // promo_name: 'Назва промо',
                // add_promo_name: 'Додати назву промо',
                out_of: 'з',
                models: 'моделей',
                in_order_to_use_this_option_you_must_log_in_or_register:
                    'Щоб скористатися цією опцією, ви повинні увійти або зареєструватися.',
                you_need_to_login: 'Потрібно увійти!',
                sended: 'Надіслано',
                store_key: 'Ключ магазину',
                enter_store_key: 'Введіть ключ магазину!',
                this_catalog_is_private_in_order_to_enter_you_must_enter_the_key:
                    'Цей каталог є приватним, щоб увійти необхідно ввести ключ каталогу.',
                this_catalog_does_not_support_the_current_language_to_continue_select_a_language_from_the_list_in_the_languages_menu:
                    'Цей каталог не підтримує поточну мову, щоб продовжити, виберіть мову зі списку в меню мов',
                language_error: 'Помилка мови!',
            },
        },
        {
            code: 'pl',
            string: {
                languages: 'Języki',
                back_to_stores: 'Wróć do sklepów',
                ok: 'Ok',
                search: 'Szukaj',
                language: 'Język',
                wrong_key: 'Niewłaściwy klucz!',
                approve: 'Zatwierdzić',
                ready: 'Gotowy',
                clear_filters: 'Wyczyść filtry',
                clear: 'Wyczyść',
                filters: 'Filtry',
                nothing_was_found: 'Nic nie zostało znalezione',
                stores: 'Sklepy',
                catalog: 'Katalog',
                polish: 'Polski',
                czech: 'Czeski',
                russian: 'Rosyjski',
                ukrainian: 'Ukraiński',
                english: 'Angielski',
                find_store_by_name: 'Znajdź sklep według nazwy',
                favorites: 'Ulubione',
                my_stores: 'Moje sklepy',
                login: 'Zaloguj się',
                register: 'Zarejestruj się',
                wrong_login_or_password: 'Błędny login lub hasło',
                forgot_password: 'Zapomniałem hasła?',
                cart: 'Koszyk',
                vendor_code: 'Kod',
                // color: 'Kolor',
                // available_sizes: 'Dostępne rozmiary',
                // go_to_details: 'Przejdź do szczegółów',
                // remove: 'Usuń', //
                price: 'Cena',
                // total_price: 'Cena całkowita',
                // total_quantity: 'Całkowita ilość',
                // add_product_sizes: 'Dodaj rozmiary produktów',
                // gallery: 'Galeria',
                // admin: 'Administrator',
                logout: 'Wyloguj',
                submit: 'Składać',
                ukraine: 'Ukraina',
                czechia: 'Czechy',
                italy: 'Włochy',
                kazakhstan: 'Kazachstan',
                poland: 'Polska',
                turkey: 'Turcja', //
                description: 'Opis',
                added: 'Dodano',
                add_to: 'Dodaj do',
                // confirm_order: 'Potwierdź zamówienie',
                // personal_data: 'Dane osobowe',
                first_name: 'Imię',
                last_name: 'Nazwisko',
                // receiver_first_name: 'Imię odbiorcy',
                // receiver_last_name: 'Nazwisko odbiorcy',
                // receiver_phone_number: 'Numer telefonu odbiorcy',
                phone_number: 'Numer telefonu',
                city: 'Miasto',
                email: 'E-mail',
                password: 'Hasło',
                confirm_password: 'Potwierdź hasło',
                company_name: 'Nazwa firmy',
                already_registered: 'Już zarejestrowany',
                do_want_to_logout: 'Czy na pewno chcesz opuścić swoje konto?',
                // delivery_information: 'Informacje o dostawie',
                // additional_information: 'Dodatkowe informacje',
                // post_office: 'Urząd Pocztowy',
                // comments: 'Komentarze', //
                // status: 'Stan',
                // ordered_date: 'Data zamówienia', //
                // delete_item: 'Usuń element',
                // do_you_want_to_delete_item: 'Czy chcesz usunąć element?',
                cancel: 'Anuluj',
                // confirm: 'Potwierdź',
                // do_you_want_to_confirm_order: 'Czy chcesz potwierdzić zamówienie?',
                // order: 'Zamówienie',
                clear_cart: 'Wyczyść koszyk',
                do_you_want_to_clear_cart: 'Czy chcesz wyczyścić koszyk?',
                // clear_favorites: 'Wyczyść ulubione',
                // do_you_want_to_clear_favorites: 'Czy chcesz wyczyścić ulubione?',
                // promo_code: 'Kod promocyjny',
                enter_password: 'Wprowadź hasło',
                enter_email: 'Wpisz email',
                enter_valid_email: 'Wprowadź prawidłowy adres e-mail',
                password_length_min_8_symbols: 'Długość hasła min. 8 znaków',
                passwords_do_not_match: 'Hasła się nie zgadzają',
                enter_first_name: 'Wpisz imię',
                enter_last_name: 'Wpisz nazwisko',
                enter_phone_number: 'Wprowadź numer telefonu',
                // login_to_order: 'Zaloguj się, aby złożyć zamówienie',
                // my_orders: 'Moje zamówienia',
                my_profile: 'Mój profil',
                // price_per_item: 'Cena za sztukę',
                country: 'Kraj',
                e_a: 'e.a.',
                reset_password: 'Zresetuj hasło',
                close: 'Zamknij',
                please_enter_your_email_address_you_will_receive_a_link_to_create_a_new_password_via_email:
                    'Podaj swój adres e-mail. Otrzymasz wiadomość e-mail z linkiem do utworzenia nowego hasła.',
                user_with_this_email_not_found: 'Nie znaleziono użytkownika z tym adresem e-mail',
                an_email_with_a_link_has_been_sent_to_your_email:
                    'E-mail z linkiem został wysłany na Twój adres e-mail',
                find_by_vendor_code: 'Znajdź według kodu dostawcy',
                // //ADMIN
                // orders_list: 'Lista zamówień',
                // customers_list: 'Lista klientów',
                // products_list: 'Lista produktów',
                // products_QR_list: 'Lista QR produktów',
                // products_options: 'Opcje produktów',
                // add_user: 'Dodaj użytkownika',
                // dashboard: 'Pulpit nawigacyjny',
                // categories: 'Kategorie',
                colors: 'Kolory',
                sizes: 'Rozmiary',
                // variants: 'Warianty',
                // id: 'ID',
                // full_name: 'Pełna nazwa', //
                // actions: 'Akcje',
                // size: 'Rozmiar',
                // quantity: 'Ilość',
                // save: 'Zapisz',
                // pledge: 'Zastaw',
                contacts: 'Kontakty',
                name: 'Nazwa',
                // completeness: 'Kompletność',
                // add_models: 'Dodaj modele',
                // add_images: 'Dodaj obrazy',
                // add_sizes: 'Dodaj rozmiary',
                // completed: 'Zakończone',
                // available: 'Dostępny',
                // create_new: 'Utwórz nowy',
                // product_data: 'Dane produktu',
                // update: 'Aktualizacja',
                // order_priority: 'Priorytet zamówienia',
                // models: 'Modele',
                // add_product_to_add_sizes: 'Dodaj produkt, aby dodać rozmiary',
                // add_product_to_add_categories: 'Dodaj produkt, aby dodać kategorie',
                // add_product_to_add_models: 'Dodaj produkt, aby dodać modele',
                // vendor_code_must_be_unique: 'Kod dostawcy musi być unikalny',
                // add: 'Dodaj',
                // delete: 'Usuń', //
                // categories_options: 'Opcje kategorii',
                // new_category_name: 'Nowa nazwa kategorii',
                // new_category_code: 'Nowy kod kategorii',
                // selected_category: 'Wybrana kategoria',
                // add_category_name: 'Dodaj nazwę kategorii',
                // root: 'Korzeń',
                // add_category_code: 'Dodaj kod kategorii',
                // colors_options: 'Opcje kolorów',
                // add_color: 'Dodaj kolor',
                // edit_color: 'Edytuj kolor',
                // add_color_name: 'Dodaj nazwę koloru',
                // option_name: 'Nazwa opcji',
                // color_code: 'Kod koloru',
                // color_name: 'Nazwa koloru',
                // available_colors: 'Dostępne kolory',
                // label: 'Etykieta',
                // code: 'Kod',
                // sizes_options: 'Opcje rozmiarów',
                // edit_size: 'Edytuj rozmia',
                // add_size: 'Dodaj rozmiar',
                // size_code: 'Kod rozmiaru',
                // size_name: 'Nazwa rozmiaru',
                // add_size_code: 'Dodaj kod rozmiaru',
                // add_size_name: 'Dodaj nazwę rozmiaru',
                // variants_options: 'Opcje wariantów',
                // add_variant_by_color: 'Dodaj wariant według koloru',
                // available_variant: 'Dostępne warianty',
                // option_code: 'Kod opcji',
                // add_option_code: 'Dodaj kod opcji',
                // option_value: 'Wartość opcji',
                // change_password: 'Zmień hasło',
                // new_password: 'Nowe hasło',
                // product_create: 'Utwórz produkt',
                // details: 'Szczegóły',
                // change_status: 'Zmień status',
                // do_you_want_to_change_order_status: 'Czy chcesz zmienić status zamówienia?',
                // leave_the_comment: 'Zostaw komentarz',
                // order_history: 'Historia zamówień',
                // products: 'Produkty',
                // //order status
                // processed: 'Przetworzone',
                // ordered: 'Zamówione',
                // delivered: 'Dostarczone',
                // refunded: 'Zwrócono',
                // canceled: 'Anulowane',
                no_results: 'Brak wyników',
                loading: 'Ładowanie',
                phone_length_minimum_7_characters: 'Długość telefonu minimum 7 znaków',
                // your_order_may_take_some_time_to_process: 'Przetwarzanie Twojego zamówienia może trochę potrwaćs',
                sizes_table: 'Tabela rozmiarów',
                // international: 'Międzynarodowy',
                // chest_girth: 'Obwód klatki piersiowej',
                // waist_circumference: 'Obwód talii',
                // hip_girth: 'Obwód bioder',
                load_more: 'Załaduj więcej',
                // promo: 'Promocja',
                // promo_options: 'Opcje promocji',
                // edit_promo: 'Edytuj promocję',
                // add_promo: 'Dodaj promocję',
                // available_promo: 'Dostępna promocja',
                // add_promo_code: 'Dodaj kod promocyjny',
                // promo_name: 'Nazwa promocji',
                // add_promo_name: 'Dodaj nazwę promocji',
                out_of: 'ze',
                models: 'modeli',
                in_order_to_use_this_option_you_must_log_in_or_register:
                    'Aby skorzystać z tej opcji należy się zalogować lub zarejestrować.',
                you_need_to_login: 'Musisz się zalogować!',
                sended: 'Wysłano',
                store_key: 'Klucz sklepu',
                enter_store_key: 'Wprowadź klucz sklepu',
                this_catalog_is_private_in_order_to_enter_you_must_enter_the_key:
                    'Ten katalog jest prywatny, aby do niego wejść, musisz wprowadzić klucz katalogu.',
                this_catalog_does_not_support_the_current_language_to_continue_select_a_language_from_the_list_in_the_languages_menu:
                    'Ten katalog nie obsługuje bieżącego języka, aby kontynuować, wybierz język z listy w menu języków',
                language_error: 'Błąd językowy!',
            },
        },
        {
            code: 'cz',
            string: {
                languages: 'Jazyky',
                back_to_stores: 'Vraťte se do obchodů',
                ok: 'Ok',
                search: 'Nalézt',
                language: 'Jazyk',
                wrong_key: 'Špatný klíč!',
                approve: 'Schvalovat',
                ready: 'Připraven',
                clear_filters: 'Vymazat filtry',
                clear: 'Vymazat',
                filters: 'Filtry',
                nothing_was_found: 'Nic nebylo nalezeno',
                stores: 'Obchody',
                catalog: 'Katalog',
                polish: 'Polština',
                czech: 'Ceština',
                russian: 'Ruština',
                ukrainian: 'Ukrajinský',
                english: 'Angličtina',
                find_store_by_name: 'Najděte obchod podle názvu',
                favorites: 'Oblíbené',
                my_stores: 'Moje obchody',
                login: 'Přihlásit',
                register: 'Registrovat',
                wrong_login_or_password: 'Chybné přihlašovací jméno nebo heslo',
                forgot_password: 'Zapomenuté heslo?',
                cart: 'Košík',
                vendor_code: 'Kód',
                // color: 'Barva',
                // available_sizes: 'Dostupné velikosti',
                // go_to_details: 'Přejít na podrobnosti',
                // remove: 'Odstranit',
                price: 'Cena',
                // total_price: 'Celková cena',
                // total_quantity: 'Celkové množství',
                // add_product_sizes: 'Přidat velikosti produktů',
                // gallery: 'Galerie',
                // admin: 'Admin',
                logout: 'Odhlásit',
                submit: 'Předložit',
                ukraine: 'Ukrajina',
                czechia: 'Czechia',
                italy: 'Itálie',
                kazakhstan: 'Kazachstán',
                poland: 'Polsko',
                turkey: 'Turecko',
                description: 'Popis',
                added: 'Přidáno',
                add_to: 'Přidat do',
                // confirm_order: 'Potvrdit objednávku',
                // personal_data: 'Osobní údaje',
                first_name: 'Křestní jméno',
                last_name: 'Příjmení',
                // receiver_first_name: 'Křestní jméno příjemce',
                // receiver_last_name: 'Příjmení příjemce',
                // receiver_phone_number: 'Telefonní číslo příjemce',
                phone_number: 'Telefonní číslo',
                city: 'Město',
                email: 'Email',
                password: 'Heslo',
                confirm_password: 'Potvrdit heslo',
                company_name: 'Název společnosti',
                already_registered: 'Již zaregistrován',
                do_want_to_logout: 'Opravdu chcete opustit svůj účet?',
                // delivery_information: 'Informace o doručení',
                // additional_information: 'Další informace',
                // post_office: 'Pošta',
                // comments: 'Komentáře',
                // status: 'Stav',
                // ordered_date: 'Datum objednávky',
                // delete_item: 'Smazat položku',
                // do_you_want_to_delete_item: 'Chcete smazat položku?',
                cancel: 'Cancel',
                // confirm: 'Potvrdit',
                // do_you_want_to_confirm_order: 'Chcete potvrdit objednávku?',
                // order: 'Objednat',
                clear_cart: 'Vymazat košík',
                do_you_want_to_clear_cart: 'Chcete vymazat košík?',
                // clear_favorites: 'Vymazat oblíbené',
                // do_you_want_to_clear_favorites: 'Chcete vymazat oblíbené položky?',
                // promo_code: 'Promo kód',
                enter_password: 'Zadejte heslo',
                enter_email: 'Zadejte e-mail',
                enter_valid_email: 'Zadejte platný e-mail',
                password_length_min_8_symbols: 'Délka hesla min 8 symbolů',
                passwords_do_not_match: 'Hesla se neshodují',
                enter_first_name: 'Zadejte křestní jméno',
                enter_last_name: 'Zadejte příjmení',
                enter_phone_number: 'Zadejte telefonní číslo',
                // login_to_order: 'Přihlášení k objednávce',
                // my_orders: 'Moje objednávky',
                my_profile: 'Můj profil',
                // price_per_item: 'Cena za položku',
                country: 'Země',
                e_a: 'e.a.',
                reset_password: 'Resetovat heslo',
                close: 'Zavřít',
                please_enter_your_email_address_you_will_receive_a_link_to_create_a_new_password_via_email:
                    'Prosím zadejte svou e-mailovou adresu. E-mailem obdržíte odkaz pro vytvoření nového hesla.',
                user_with_this_email_not_found: 'Uživatel s tímto e-mailem nebyl nalezen',
                an_email_with_a_link_has_been_sent_to_your_email: 'Na váš e-mail byl odeslán e-mail s odkazem',
                find_by_vendor_code: 'Najít podle kódu dodavatele',
                // //ADMIN
                // orders_list: 'Seznam objednávek',
                // customers_list: 'Seznam zákazníků',
                // products_list: 'Seznam produktů',
                // products_QR_list: 'Seznam QR produktů',
                // products_options: 'Možnosti produktů',
                // add_user: 'Přidat uživatele',
                // dashboard: 'Dashboard',
                // categories: 'Kategorie',
                colors: 'Barvy',
                sizes: 'Velikosti',
                // variants: 'Varianty',
                // id: 'ID',
                // full_name: 'Celé jméno',
                // actions: 'Akce',
                // size: 'Velikost',
                // quantity: 'Množství',
                // save: 'Uložit',
                // pledge: 'Pledge',
                contacts: 'Kontakty',
                name: 'Jméno',
                // completeness: 'Uplnost',
                // add_models: 'Přidat modely',
                // add_images: 'Přidat obrázky',
                // add_sizes: 'Přidat velikosti',
                // completed: 'Dokončeno',
                // available: 'Dostupné',
                // create_new: 'Vytvořit nový',
                // product_data: 'Produktová data',
                // update: 'Aktualizovat',
                // order_priority: 'Priorita objednávky',
                // models: 'Modely',
                // add_product_to_add_sizes: 'Přidat produkt k přidání velikostí',
                // add_product_to_add_categories: 'Přidat produkt k přidání kategorií',
                // add_product_to_add_models: 'Přidat produkt k přidání modelů',
                // vendor_code_must_be_unique: 'Kód dodavatele musí být jedinečný',
                // add: 'Přidat',
                // delete: 'Smazat',
                // categories_options: 'Možnosti kategorií',
                // new_category_name: 'Název nové kategorie',
                // new_category_code: 'Kód nové kategorie',
                // selected_category: 'Vybraná kategorie',
                // add_category_name: 'Přidat název kategorie',
                // root: 'kořen',
                // add_category_code: 'Přidat kód kategorie',
                // colors_options: 'Možnosti barev',
                // add_color: 'Přidat barvu',
                // edit_color: 'Upravit barvu',
                // add_color_name: 'Přidat název barvy',
                // option_name: 'Název možnosti',
                // color_code: 'kód barvy',
                // color_name: 'Název barvy',
                // available_colors: 'Dostupné barvy',
                // label: 'Stítek',
                // code: 'Kód',
                // sizes_options: 'Možnosti velikostí',
                // edit_size: 'Upravit velikost',
                // add_size: 'Přidat velikost',
                // size_code: 'Kód velikosti',
                // size_name: 'Název velikosti',
                // add_size_code: 'Přidat kód velikosti',
                // add_size_name: 'Přidat název velikosti',
                // variants_options: 'Možnosti variant',
                // add_variant_by_color: 'Přidat variantu podle barvy',
                // available_variant: 'Dostupné varianty',
                // option_code: 'Kód možnosti',
                // add_option_code: 'Přidat kód volby',
                // option_value: 'Hodnota možnosti',
                // change_password: 'Změnit heslo',
                // new_password: 'Nové heslo',
                // product_create: 'Vytvoření produktu',
                // details: 'Podrobnosti',
                // change_status: 'Změnit stav',
                // do_you_want_to_change_order_status: 'Chcete změnit stav objednávky?',
                // leave_the_comment: 'Zanechat komentář',
                // order_history: 'Historie objednávek',
                // products: 'Produkty',
                // //order status
                // processed: 'Zpracováno',
                // ordered: 'Objednáno',
                // delivered: 'Doručeno',
                // refunded: 'Refunded',
                // canceled: 'Zrušeno',
                no_results: 'Žádné výsledky',
                loading: 'Načítání',
                phone_length_minimum_7_characters: 'Minimální délka telefonu 7 znaků',
                // your_order_may_take_some_time_to_process: 'Zpracování vaší objednávky může nějakou dobu trvat',
                sizes_table: 'Tabulka velikostí',
                // international: 'International',
                // chest_girth: 'Obvod hrudníku',
                // waist_circumference: 'Obvod pasu',
                // hip_girth: 'Obvod boků',
                load_more: 'Načíst více',
                // promo: 'Promo',
                // promo_options: 'Promo propagace',
                // edit_promo: 'Upravit Promo',
                // add_promo: 'Přidat Promo',
                // available_promo: 'Dostupná Promo',
                // add_promo_code: 'Přidat propagační kód',
                // promo_name: 'Název promo akce',
                // add_promo_name: 'Přidat název propagace',
                out_of: 'ze',
                models: 'modelů',
                in_order_to_use_this_option_you_must_log_in_or_register:
                    'Abyste mohli tuto možnost využít, musíte se přihlásit nebo zaregistrovat.',
                you_need_to_login: 'Musíte se přihlásit!',
                sended: 'Odesláno',
                store_key: 'Klíč obchodu',
                enter_store_key: 'Zadejte klíč obchodu!',
                this_catalog_is_private_in_order_to_enter_you_must_enter_the_key:
                    'Tento adresář je soukromý, pro vstup musíte zadat klíč adresáře.',
                this_catalog_does_not_support_the_current_language_to_continue_select_a_language_from_the_list_in_the_languages_menu:
                    'Tento katalog nepodporuje aktuální jazyk, pro pokračování vyberte jazyk ze seznamu v nabídce jazyků',
                language_error: 'Jazyková chyba!',
            },
        },
        {
            code: 'ru',
            string: {
                languages: 'Языки',
                back_to_stores: 'Вернуться к магазинам',
                ok: 'Ок',
                search: 'Поиск',
                language: 'Язык',
                wrong_key: 'Неверный ключ!',
                approve: 'Подтвердить',
                ready: 'Готово',
                clear_filters: 'Очистить филтры',
                clear: 'Очистить',
                filters: 'Фильтры',
                nothing_was_found: 'Ничего не найдено',
                stores: 'Магазины',
                catalog: 'Каталог',
                polish: 'Польский',
                czech: 'Чешский',
                russian: 'Русский',
                ukrainian: 'Украинский',
                english: 'Английский',
                find_store_by_name: 'Найти магазин по названию',
                favorites: 'Избранное',
                my_stores: 'Мои магазины',
                login: 'Вход',
                register: 'Регистрация',
                wrong_login_or_password: 'Неверный логин или пароль',
                forgot_password: 'Забыл пароль?',
                cart: 'Корзина',
                vendor_code: 'Артикул',
                // color: 'Цвет',
                // available_sizes: 'Доступные размеры',
                // go_to_details: 'Перейти к описанию',
                // remove: 'Удалить',
                price: 'Цена',
                // total_price: 'Общая сумма',
                // total_quantity: 'Общее количество',
                // add_product_sizes: 'Добавить размер',
                // gallery: 'Галлерея',
                // admin: 'Админ',
                logout: 'Выход',
                submit: 'Подтвердить',
                ukraine: 'Украина',
                czechia: 'Чехия',
                italy: 'Италия',
                kazakhstan: 'Казахстан',
                poland: 'Польша',
                turkey: 'Турция',
                description: 'Описание',
                added: 'Добавлено',
                add_to: 'Добавить в',
                // confirm_order: 'Подтвердить заказ',
                // personal_data: 'Персональные данные',
                first_name: 'Имя',
                last_name: 'Фамилия',
                // receiver_first_name: 'Имя получателя',
                // receiver_last_name: 'Фамилия получателя',
                // receiver_phone_number: 'Номер телефона получателя',
                phone_number: 'Номер телефона',
                city: 'Город',
                email: 'Email',
                password: 'Пароль',
                confirm_password: 'Подтвердить пароль',
                company_name: 'Имя компании',
                already_registered: 'Уже зарегестрирован',
                do_want_to_logout: 'Вы действительно хотите покинуть аккаунт?',
                // delivery_information: 'Информация доставки',
                // additional_information: 'Дополнительная информацияn',
                // post_office: 'Почтовое отделение',
                // comments: 'Коментарий',
                // status: 'StatСтатусus',
                // ordered_date: 'Дата заказа',
                // delete_item: 'Удалить',
                // do_you_want_to_delete_item: 'Вы хотите удалить?',
                cancel: 'Отмена',
                // confirm: 'Подтвердить',
                // do_you_want_to_confirm_order: 'Вы хотите подтвердить заказ?',
                // order: 'Заказ',
                clear_cart: 'Очистить корзину',
                do_you_want_to_clear_cart: 'Вы хотите очистить корзину?',
                // clear_favorites: 'Очистить избранное',
                // do_you_want_to_clear_favorites: 'Вы хотите очистить избранное?',
                // promo_code: 'Промо код',
                enter_password: 'Введите пароль',
                enter_email: 'Введите email',
                enter_valid_email: 'Введите корректный email',
                password_length_min_8_symbols: 'Пароль должен быть не менее 8 символов',
                passwords_do_not_match: 'Пароли не совпадают',
                enter_first_name: 'Введите имя',
                enter_last_name: 'Введите фамилию',
                enter_phone_number: 'Введите номер телефона',
                // login_to_order: 'Войти для заказа',
                // my_orders: 'Мои заказы',
                my_profile: 'Профиль',
                // price_per_item: 'Цена еденицы',
                country: 'Страна',
                e_a: 'ед.',
                reset_password: 'Сбросить пароль',
                close: 'Закрыть',
                please_enter_your_email_address_you_will_receive_a_link_to_create_a_new_password_via_email:
                    'Пожалуйста, введите Ваш адрес электронной почты. Вы получите ссылку для создания нового пароля по электронной почте.',
                user_with_this_email_not_found: 'Пользователь с этим адресом электронной почты не найден',
                an_email_with_a_link_has_been_sent_to_your_email:
                    'На ваш адрес электронной почты отправлено письмо со ссылкой',
                find_by_vendor_code: 'Найти по артикулу',
                // //ADMIN
                // orders_list: 'Список заказов',
                // customers_list: 'Список клиентов',
                // products_list: 'Список товара',
                // products_QR_list: 'QR коды товара',
                // products_options: 'Опции',
                // add_user: 'Добавить пользователя',
                // dashboard: 'Доска',
                // categories: 'Категории',
                colors: 'Цвета',
                sizes: 'Размеры',
                // variants: 'Варианты',
                // id: 'ID',
                // full_name: 'Имя',
                // actions: 'Действия',
                // size: 'Размер',
                // quantity: 'Количество',
                // save: 'Сохранить',
                // pledge: 'Pledge',
                contacts: 'Контакты',
                name: 'Имя',
                // completeness: 'Заполненность',
                // add_models: 'Добавить модель',
                // add_images: 'Добавить изображение',
                // add_sizes: 'Добавить размер',
                // completed: 'Готово',
                // available: 'Доступно',
                // create_new: 'Создать новый',
                // product_data: 'Данные товара',
                // update: 'Обновить',
                // order_priority: 'Приоритет',
                // models: 'Модели',
                // add_product_to_add_sizes: 'Добавить продукт',
                // add_product_to_add_categories: 'Добавить продукт',
                // add_product_to_add_models: 'Добавить продукт',
                // vendor_code_must_be_unique: 'Артикул существует',
                // add: 'Добавить',
                // delete: 'Удалить',
                // categories_options: 'Опции категорий',
                // new_category_name: 'Имя категории',
                // new_category_code: 'Код категории',
                // selected_category: 'Выбранная категория',
                // add_category_name: 'Добавить имя категории',
                // root: 'Корень',
                // add_category_code: 'Добавить код категории',
                // colors_options: 'Опции цветов',
                // add_color: 'Добавить цвет',
                // edit_color: 'Редактировать цвет',
                // add_color_name: 'Добавить имя цвета',
                // option_name: 'Имя опции',
                // color_code: 'Код цвета',
                // color_name: 'Имя цвета',
                // available_colors: 'доступные цвета',
                // label: 'Лейба',
                // code: 'Код',
                // sizes_options: 'Опции размеров',
                // edit_size: 'Редактировать размер',
                // add_size: 'Добавить размер',
                // size_code: 'Кодразмера',
                // size_name: 'Имя размера',
                // add_size_code: 'Добавить код размера',
                // add_size_name: 'Добавить имя размера',
                // variants_options: 'Опции вариайций',
                // add_variant_by_color: 'Добавить вариант по цвету',
                // available_variant: 'Доступные варианты',
                // option_code: 'Код опции',
                // add_option_code: 'Добавить код опции',
                // option_value: 'Значение опции',
                // change_password: 'Изменить пароль',
                // new_password: 'Новый пароль',
                // product_create: 'Создать продукт',
                // details: 'Детали',
                // change_status: 'Изменить статус',
                // do_you_want_to_change_order_status: 'Хотите изменит статус?',
                // leave_the_comment: 'Оставить комментарий',
                // order_history: 'История заказа',
                // products: 'Товар',
                // //order status
                // processed: 'Готовится',
                // ordered: 'Заказано',
                // delivered: 'Доставлено',
                // refunded: 'Возврат',
                // canceled: 'Отменен',
                no_results: 'Нет результатов',
                loading: 'Загрузка',
                phone_length_minimum_7_characters: 'минимум 7 символов',
                // your_order_may_take_some_time_to_process: 'Может занять несколько минут',
                sizes_table: 'Таблица размеров',
                // international: 'Муждународный',
                // chest_girth: 'Обхват груди',
                // waist_circumference: 'Обхват талии',
                // hip_girth: 'Обхват бедер',
                load_more: 'Загрузить  еще',
                // promo: 'Промо',
                // promo_options: 'Опции промо',
                // edit_promo: 'Редактировать промо',
                // add_promo: 'Добавить промо',
                // available_promo: 'Доступные промо',
                // add_promo_code: 'Добавить промо код',
                // promo_name: 'Имя промо',
                // add_promo_name: 'Добавить имя промо',
                out_of: 'из',
                models: 'моделей',
                in_order_to_use_this_option_you_must_log_in_or_register:
                    'Для того, чтобы воспользоваться этой опцией, вам необходимо войти или зарегистрироваться.',
                you_need_to_login: 'Необходимо войти!',
                sended: 'Отправлено',
                store_key: 'Ключ магазина',
                enter_store_key: 'Введите ключ магазина!',
                this_catalog_is_private_in_order_to_enter_you_must_enter_the_key:
                    'Этот каталог приватный, для того чтобы войти вы должны ввести ключ.',
                this_catalog_does_not_support_the_current_language_to_continue_select_a_language_from_the_list_in_the_languages_menu:
                    'Этот каталог не поддерживает текущий язык, для продолжения выберите язык из списка в меню языков',
                language_error: 'Ошибка языка!',
            },
        },
    ];

    useEffect(() => {
        setCurrentLanguage(langList.find(({ code }) => code === lang));
    }, [lang]);

    return { currentLanguage };
};
