import { ALBERTO_BINI_MAIN_DB } from './stores_db/ALBERTO_BINI_MAIN_DB';
import { ALBERTO_BINI_OUTLET_DB } from './stores_db/ALBERTO_BINI_OUTLET_DB';
import { ALBERTO_BINI_SALES_DB } from './stores_db/ALBERTO_BINI_SALES_DB';
import { KREMEN_BELTS_MAIN_DB } from './stores_db/KREMEN_BELTS_MAIN_DB';
import { KREMEN_BELTS_SALES_DB } from './stores_db/KREMEN_BELTS_SALES_DB';

export const STORES_DATA = [
    ALBERTO_BINI_MAIN_DB,
    ALBERTO_BINI_OUTLET_DB,
    KREMEN_BELTS_MAIN_DB,
    ALBERTO_BINI_SALES_DB,
    KREMEN_BELTS_SALES_DB,
];
