export const STORES_DATA = [
    {
        code: 'Carvela',
        mainImage: require('./images/w-shoes.jpg'),
        productImagesOptions: { width: 6, height: 8, cropX: 0, cropY: 0 },
        descriptions: [
            {
                language: 'ua',
                name: 'UA name',
                description: 'UA description',
                friendlyUrl: 'UA description',
                keyWords: 'UA description',
                highlights: 'UA description',
                metaDescription: 'UA description',
                title: 'Магазин жiночого взуття',
            },
            {
                language: 'en',
                name: 'EN name',
                description: 'EN description',
                friendlyUrl: 'EN description',
                keyWords: 'EN description',
                highlights: 'EN description',
                metaDescription: 'EN description',
                title: 'Store of Women`s Shoes',
            },
            {
                language: 'fr',
                name: 'FR name',
                description: 'FR description',
                friendlyUrl: 'FR description',
                keyWords: 'FR description',
                highlights: 'FR description',
                metaDescription: 'FR description',
                title: 'Magasin de chaussures pour femmes',
            },
        ],
        mainStoreSettings: {
            skuSearch: true,
            colors: true,
            prices: true,
            sizes: true,
            contacts: true,
            categories: true,
            browserSearch: true,
            productShare: true,
        },
        additionalStoreSettings: {
            cart: true,
            favorites: true,
            promo: true,
            video: true,
            tableSizes: true,
            callback: true,
            platformAvailable: true,
            appleStore: true,
            playMarket: true,
        },
        dataBaseStoreSettings: { users: 5, products: 50, productModels: 5, photos: 5, videos: 1 },
        securityStoreSettings: { private: false, securityKey: null },
        storeProductTypes: [
            {
                code: 'Shoes',
            },
        ],
    },
    {
        code: 'DEFAULT',
        mainImage: require('./images/alb.jpeg'),
        productImagesOptions: { width: 6, height: 8, cropX: 0, cropY: 0 },
        descriptions: [
            {
                language: 'ua',
                name: 'UA name',
                description: 'UA description',
                friendlyUrl: 'UA description',
                keyWords: 'UA description',
                highlights: 'UA description',
                metaDescription: 'UA description',
                title: 'Магазин жiночого одягу',
            },
            {
                language: 'en',
                name: 'EN name',
                description: 'EN description',
                friendlyUrl: 'EN description',
                keyWords: 'EN description',
                highlights: 'EN description',
                metaDescription: 'EN description',
                title: 'Store of Women`s Clothes',
            },
            {
                language: 'pl',
                name: 'PL name',
                description: 'PL description',
                friendlyUrl: 'PL description',
                keyWords: 'PL description',
                highlights: 'PL description',
                metaDescription: 'PL description',
                title: 'Sklep z odzieżą damską',
            },
        ],
        mainStoreSettings: {
            skuSearch: true,
            colors: true,
            prices: true,
            sizes: true,
            contacts: true,
            categories: true,
            browserSearch: true,
            productShare: true,
        },
        additionalStoreSettings: {
            cart: true,
            favorites: true,
            promo: true,
            video: true,
            tableSizes: true,
            callback: true,
            platformAvailable: true,
            appleStore: true,
            playMarket: true,
        },
        dataBaseStoreSettings: { users: 5, products: 50, productModels: 5, photos: 5, videos: 1 },
        securityStoreSettings: { private: false, securityKey: null },
        storeProductTypes: [
            {
                code: 'Outerwear',
            },
            {
                code: 'Women clothes',
            },
        ],
    },
    {
        code: 'Test',
        mainImage: require('./images/bags.jpeg'),
        productImagesOptions: { width: 6, height: 8, cropX: 0, cropY: 0 },
        descriptions: [
            {
                language: 'ua',
                name: 'UA name',
                description: 'UA description',
                friendlyUrl: 'UA description',
                keyWords: 'UA description',
                highlights: 'UA description',
                metaDescription: 'UA description',
                title: 'Магазин жіночих сумок',
            },
            {
                language: 'en',
                name: 'EN name',
                description: 'EN description',
                friendlyUrl: 'EN description',
                keyWords: 'EN description',
                highlights: 'EN description',
                metaDescription: 'EN description',
                title: 'Store of Women`s Bags',
            },
            {
                language: 'cz',
                name: 'CZ name',
                description: 'CZ description',
                friendlyUrl: 'CZ description',
                keyWords: 'CZ description',
                highlights: 'CZ description',
                metaDescription: 'CZ description',
                title: 'Prodejna dámských tašek',
            },
        ],
        mainStoreSettings: {
            skuSearch: true,
            colors: true,
            prices: true,
            sizes: true,
            contacts: true,
            categories: true,
            browserSearch: true,
            productShare: true,
        },
        additionalStoreSettings: {
            cart: true,
            favorites: true,
            promo: true,
            video: true,
            tableSizes: true,
            callback: true,
            platformAvailable: true,
            appleStore: true,
            playMarket: true,
        },
        dataBaseStoreSettings: { users: 5, products: 50, productModels: 5, photos: 5, videos: 1 },
        securityStoreSettings: { private: false, securityKey: null },
        storeProductTypes: [
            {
                code: 'Bags',
            },
        ],
    },
    {
        code: 'KREMEN',
        mainImage: require('./images/belts.jpeg'),
        productImagesOptions: { width: 4, height: 3, cropX: 0, cropY: 0 },
        descriptions: [
            {
                language: 'ua',
                name: 'UA name',
                description: 'UA description',
                friendlyUrl: 'UA description',
                keyWords: 'UA description',
                highlights: 'UA description',
                metaDescription: 'UA description',
                title: 'Магазин Ременів та Шкіряних Аксесуарів',
            },
            {
                language: 'en',
                name: 'EN name',
                description: 'EN description',
                friendlyUrl: 'EN description',
                keyWords: 'EN description',
                highlights: 'EN description',
                metaDescription: 'EN description',
                title: 'Belts and Leather Accessories Store',
            },
            {
                language: 'ru',
                name: 'RU name',
                description: 'RU description',
                friendlyUrl: 'RU description',
                keyWords: 'RU description',
                highlights: 'RU description',
                metaDescription: 'RU description',
                title: 'Магазин Ремней и Кожаных Аксессуаров',
            },
        ],
        mainStoreSettings: {
            skuSearch: false,
            colors: true,
            prices: false,
            sizes: false,
            contacts: false,
            categories: false,
            browserSearch: true,
            productShare: false,
        },
        additionalStoreSettings: {
            cart: false,
            favorites: false,
            promo: false,
            video: false,
            tableSizes: false,
            callback: false,
            platformAvailable: true,
            appleStore: false,
            playMarket: false,
        },
        dataBaseStoreSettings: { users: 5, products: 50, productModels: 10, photos: 5, videos: 1 },
        securityStoreSettings: { private: false, securityKey: null },
        storeProductTypes: [
            {
                code: 'Belts',
            },
        ],
    },
    {
        code: 'johnlewis',
        mainImage: require('./images/johnlewis.jpg'),
        productImagesOptions: { width: 6, height: 8, cropX: 0, cropY: 0 },
        descriptions: [
            {
                language: 'ua',
                name: 'UA name',
                description: 'UA description',
                friendlyUrl: 'UA description',
                keyWords: 'UA description',
                highlights: 'UA description',
                metaDescription: 'UA description',
                title: 'Магазин жiночого одягу',
            },
            {
                language: 'en',
                name: 'EN name',
                description: 'EN description',
                friendlyUrl: 'EN description',
                keyWords: 'EN description',
                highlights: 'EN description',
                metaDescription: 'EN description',
                title: 'Store of Women`s Clothes',
            },
            {
                language: 'es',
                name: 'ES name',
                description: 'ES description',
                friendlyUrl: 'ES description',
                keyWords: 'ES description',
                highlights: 'ES description',
                metaDescription: 'ES description',
                title: 'Tienda de ropa de mujer',
            },
        ],
        mainStoreSettings: {
            skuSearch: true,
            colors: true,
            prices: true,
            sizes: true,
            contacts: true,
            categories: true,
            browserSearch: true,
            productShare: true,
        },
        additionalStoreSettings: {
            cart: true,
            favorites: true,
            promo: true,
            video: true,
            tableSizes: true,
            callback: true,
            platformAvailable: true,
            appleStore: true,
            playMarket: true,
        },
        dataBaseStoreSettings: { users: 5, products: 50, productModels: 5, photos: 5, videos: 1 },
        securityStoreSettings: { private: true, securityKey: '1111' },
        storeProductTypes: [
            {
                code: 'Women clothes',
            },
        ],
    },
];
