export const STORES_DATA = [
    {
        code: 'ALBERTO_BINI',
        appStoreUrl: '',
        playMarketUrl: '',
        webUrl: 'https://cocktail-catalog.netlify.app',
        mainImage: require('./images/w-shoes.jpg'),
        productImagesOptions: { width: 6, height: 8, cropX: 0, cropY: 0 },
        descriptions: [
            {
                language: 'ua',
                name: 'UA name',
                description: 'UA description',
                friendlyUrl: 'UA description',
                keyWords: 'UA description',
                highlights: 'UA description',
                metaDescription: 'UA description',
                title: 'Магазин жiночого взуття',
            },
            {
                language: 'en',
                name: 'EN name',
                description: 'EN description',
                friendlyUrl: 'EN description',
                keyWords: 'EN description',
                highlights: 'EN description',
                metaDescription: 'EN description',
                title: 'Store of Women`s Shoes',
            },
            {
                language: 'fr',
                name: 'FR name',
                description: 'FR description',
                friendlyUrl: 'FR description',
                keyWords: 'FR description',
                highlights: 'FR description',
                metaDescription: 'FR description',
                title: 'Magasin de chaussures pour femmes',
            },
        ],
        mainStoreSettings: {
            skuSearch: true,
            colors: true,
            prices: true,
            sizes: true,
            contacts: true,
            categories: true,
            browserSearch: true,
            productShare: true,
        },
        additionalStoreSettings: {
            cart: true,
            favorites: true,
            promo: true,
            video: false,
            tableSizes: false,
            callback: true,
            platformAvailable: true,
            appleStore: true,
            playMarket: true,
        },
        dataBaseStoreSettings: { users: 5, products: 200, productModels: 5, photos: 5, videos: 1 },
        securityStoreSettings: { private: false, securityKey: null },
        storeProductTypes: [
            {
                code: 'Shoes',
            },
            { code: 'Women clothes' },
        ],
        managers: [
            {
                firstName: 'Dmytro',
                lastName: 'Orgish',
                emailAddress: 'dmytro.orgish88@gmail.com',
                options: { manager: true },
                contacts: {
                    emailAddress: 'dmytro.orgish88@gmail.com',
                    phone: '+380665738771',
                    viber: '+380665738771',
                    whatsapp: '+380665738771',
                    telegram: 'https://t.me/@DmytroOrgish',
                },
            },
        ],
    },
    {
        code: 'DEFAULT',
        appStoreUrl: '',
        playMarketUrl: '',
        webUrl: 'https://cocktail-catalog.netlify.app',
        mainImage: require('./images/alb.jpeg'),
        productImagesOptions: { width: 6, height: 9, cropX: 0, cropY: 20 },
        descriptions: [
            {
                language: 'ua',
                name: 'Магазин жiночого одягу',
                description: 'Магазин жiночого одягу',
                friendlyUrl: 'Магазин жiночого одягу',
                keyWords: 'Магазин жiночого одягу',
                highlights: 'Магазин жiночого одягу',
                metaDescription: 'Магазин жiночого одягу',
                title: 'Магазин жiночого одягу',
            },
            {
                language: 'en',
                name: 'Store of Women`s Clothes',
                description: 'Store of Women`s Clothes',
                friendlyUrl: 'Store of Women`s Clothes',
                keyWords: 'Store of Women`s Clothes',
                highlights: 'Store of Women`s Clothes',
                metaDescription: 'Store of Women`s Clothes',
                title: 'Store of Women`s Clothes',
            },
            {
                language: 'ru',
                name: 'Магазин Женской Одежды',
                description: 'Магазин Женской Одежды',
                friendlyUrl: 'Магазин Женской Одежды',
                keyWords: 'Магазин Женской Одежды',
                highlights: 'Магазин Женской Одежды',
                metaDescription: 'Магазин Женской Одежды',
                title: 'Магазин Женской Одежды',
            },
        ],
        mainStoreSettings: {
            skuSearch: true,
            colors: true,
            prices: true,
            sizes: true,
            contacts: true,
            categories: true,
            browserSearch: true,
            productShare: true,
        },
        additionalStoreSettings: {
            cart: true,
            favorites: true,
            promo: true,
            video: false,
            tableSizes: true,
            callback: true,
            platformAvailable: true,
            appleStore: false,
            playMarket: false,
            analytics: true,
        },
        dataBaseStoreSettings: { users: 5, products: 200, productModels: 10, photos: 10, videos: 1 },
        securityStoreSettings: { private: false, securityKey: null },
        storeProductTypes: [
            {
                code: 'Outerwear',
            },
            {
                code: 'Women clothes',
            },
        ],
        managers: [
            {
                firstName: 'Elena',
                lastName: '',
                emailAddress: 'alb-admin@mail.com',
                options: { manager: true },
                contacts: {
                    emailAddress: '',
                    phone: '+380983080085',
                    viber: '+380983080085',
                    whatsapp: '+380983080085',
                    telegram: 'Albertobiniopt',
                },
            },
        ],
    },
];
