export const STORES_DATA = [
    {
        code: 'Carvela',
        webUrl: 'https://cocktail-catalog.netlify.app',
        mainImage: require('./images/w-shoes.jpg'),
        productImagesOptions: { width: 6, height: 8, cropX: 0, cropY: 0 },
        descriptions: [
            {
                language: 'ua',
                name: 'UA name',
                description: 'UA description',
                friendlyUrl: 'UA description',
                keyWords: 'UA description',
                highlights: 'UA description',
                metaDescription: 'UA description',
                title: 'Магазин жiночого взуття',
            },
            {
                language: 'en',
                name: 'EN name',
                description: 'EN description',
                friendlyUrl: 'EN description',
                keyWords: 'EN description',
                highlights: 'EN description',
                metaDescription: 'EN description',
                title: 'Store of Women`s Shoes',
            },
            {
                language: 'fr',
                name: 'FR name',
                description: 'FR description',
                friendlyUrl: 'FR description',
                keyWords: 'FR description',
                highlights: 'FR description',
                metaDescription: 'FR description',
                title: 'Magasin de chaussures pour femmes',
            },
        ],
        mainStoreSettings: {
            skuSearch: true,
            colors: true,
            prices: true,
            sizes: true,
            contacts: true,
            categories: true,
            browserSearch: true,
            productShare: true,
        },
        additionalStoreSettings: {
            cart: true,
            favorites: true,
            promo: true,
            video: false,
            tableSizes: false,
            callback: true,
            platformAvailable: true,
            appleStore: true,
            playMarket: true,
        },
        dataBaseStoreSettings: { users: 5, products: 50, productModels: 5, photos: 5, videos: 1 },
        securityStoreSettings: { private: false, securityKey: null },
        storeProductTypes: [
            {
                code: 'Shoes',
            },
            { code: 'Women clothes' },
        ],
        managers: [
            {
                firstName: 'Dmytro',
                lastName: 'Orgish',
                emailAddress: 'dmytro.orgish88@gmail.com',
                options: { manager: true },
                contacts: {
                    emailAddress: 'dmytro.orgish88@gmail.com',
                    phone: '+380665738771',
                    viber: '+380665738771',
                    whatsapp: '+380665738771',
                    telegram: 'https://t.me/@DmytroOrgish',
                },
            },
        ],
    },
    {
        code: 'DEFAULT',
        webUrl: 'https://cocktail-catalog.netlify.app',
        mainImage: require('./images/alb.jpeg'),
        productImagesOptions: { width: 6, height: 8, cropX: 0, cropY: 20 },
        descriptions: [
            {
                language: 'ua',
                name: 'UA name',
                description: 'UA description',
                friendlyUrl: 'UA description',
                keyWords: 'UA description',
                highlights: 'UA description',
                metaDescription: 'UA description',
                title: 'Магазин жiночого одягу',
            },
            {
                language: 'en',
                name: 'EN name',
                description: 'EN description',
                friendlyUrl: 'EN description',
                keyWords: 'EN description',
                highlights: 'EN description',
                metaDescription: 'EN description',
                title: 'Store of Women`s Clothes',
            },
            {
                language: 'pl',
                name: 'PL name',
                description: 'PL description',
                friendlyUrl: 'PL description',
                keyWords: 'PL description',
                highlights: 'PL description',
                metaDescription: 'PL description',
                title: 'Sklep z odzieżą damską',
            },
        ],
        mainStoreSettings: {
            skuSearch: true,
            colors: true,
            prices: true,
            sizes: true,
            contacts: true,
            categories: true,
            browserSearch: true,
            productShare: true,
        },
        additionalStoreSettings: {
            cart: true,
            favorites: true,
            promo: true,
            video: false,
            tableSizes: true,
            callback: true,
            platformAvailable: true,
            appleStore: true,
            playMarket: true,
        },
        dataBaseStoreSettings: { users: 5, products: 50, productModels: 5, photos: 5, videos: 1 },
        securityStoreSettings: { private: false, securityKey: null },
        storeProductTypes: [
            {
                code: 'Outerwear',
            },
            {
                code: 'Women clothes',
            },
        ],
        managers: [
            {
                firstName: 'Dmytro',
                lastName: 'Orgish',
                emailAddress: 'dmytro.orgish88@gmail.com',
                options: { manager: true },
                contacts: {
                    emailAddress: 'dmytro.orgish88@gmail.com',
                    phone: '+380665738771',
                    viber: '+380665738771',
                    whatsapp: '+380665738771',
                    telegram: 'https://t.me/@DmytroOrgish',
                },
            },
        ],
    },
    {
        code: 'Test',
        webUrl: 'https://cocktail-catalog.netlify.app',
        mainImage: require('./images/bags.jpeg'),
        productImagesOptions: { width: 6, height: 8, cropX: 0, cropY: 0 },
        descriptions: [
            {
                language: 'ua',
                name: 'UA name',
                description: 'UA description',
                friendlyUrl: 'UA description',
                keyWords: 'UA description',
                highlights: 'UA description',
                metaDescription: 'UA description',
                title: 'Магазин жіночих сумок',
            },
            {
                language: 'en',
                name: 'EN name',
                description: 'EN description',
                friendlyUrl: 'EN description',
                keyWords: 'EN description',
                highlights: 'EN description',
                metaDescription: 'EN description',
                title: 'Store of Women`s Bags',
            },
            {
                language: 'cz',
                name: 'CZ name',
                description: 'CZ description',
                friendlyUrl: 'CZ description',
                keyWords: 'CZ description',
                highlights: 'CZ description',
                metaDescription: 'CZ description',
                title: 'Prodejna dámských tašek',
            },
        ],
        mainStoreSettings: {
            skuSearch: true,
            colors: true,
            prices: true,
            sizes: false,
            contacts: true,
            categories: true,
            browserSearch: true,
            productShare: true,
        },
        additionalStoreSettings: {
            cart: true,
            favorites: true,
            promo: true,
            video: false,
            tableSizes: false,
            callback: true,
            platformAvailable: true,
            appleStore: true,
            playMarket: true,
        },
        dataBaseStoreSettings: { users: 5, products: 50, productModels: 5, photos: 5, videos: 1 },
        securityStoreSettings: { private: false, securityKey: null },
        storeProductTypes: [
            {
                code: 'Bags',
            },
            { code: 'Women clothes' },
        ],
        managers: [
            {
                firstName: 'Dmytro',
                lastName: 'Orgish',
                emailAddress: 'dmytro.orgish88@gmail.com',
                options: { manager: true },
                contacts: {
                    emailAddress: 'dmytro.orgish88@gmail.com',
                    phone: '+380665738771',
                    viber: '+380665738771',
                    whatsapp: '+380665738771',
                    telegram: 'https://t.me/@DmytroOrgish',
                },
            },
        ],
    },
    {
        code: 'KREMEN',
        webUrl: 'https://cocktail-catalog.netlify.app',
        mainImage: require('./images/belts.jpeg'),
        productImagesOptions: { width: 4, height: 3, cropX: 0, cropY: 0 },
        descriptions: [
            {
                language: 'ua',
                name: 'UA name',
                description: 'UA description',
                friendlyUrl: 'UA description',
                keyWords: 'UA description',
                highlights: 'UA description',
                metaDescription: 'UA description',
                title: 'Магазин Ременів та Шкіряних Аксесуарів',
            },
            {
                language: 'en',
                name: 'EN name',
                description: 'EN description',
                friendlyUrl: 'EN description',
                keyWords: 'EN description',
                highlights: 'EN description',
                metaDescription: 'EN description',
                title: 'Belts and Leather Accessories Store',
            },
            {
                language: 'ru',
                name: 'RU name',
                description: 'RU description',
                friendlyUrl: 'RU description',
                keyWords: 'RU description',
                highlights: 'RU description',
                metaDescription: 'RU description',
                title: 'Магазин Ремней и Кожаных Аксессуаров',
            },
        ],
        mainStoreSettings: {
            skuSearch: true,
            colors: true,
            prices: true,
            sizes: false,
            contacts: true,
            categories: true,
            browserSearch: true,
            productShare: true,
        },
        additionalStoreSettings: {
            cart: true,
            favorites: true,
            promo: true,
            video: false,
            tableSizes: false,
            callback: true,
            platformAvailable: true,
            appleStore: false,
            playMarket: false,
        },
        dataBaseStoreSettings: { users: 5, products: 50, productModels: 10, photos: 5, videos: 1 },
        securityStoreSettings: { private: false, securityKey: null },
        storeProductTypes: [
            {
                code: 'Belts',
            },
        ],
        managers: [
            {
                firstName: 'Dmytro',
                lastName: 'Orgish',
                emailAddress: 'dmytro.orgish88@gmail.com',
                options: { manager: true },
                contacts: {
                    emailAddress: 'dmytro.orgish88@gmail.com',
                    phone: '+380665738771',
                    viber: '+380665738771',
                    whatsapp: '+380665738771',
                    telegram: 'https://t.me/@DmytroOrgish',
                },
            },
        ],
    },
    {
        code: 'johnlewis',
        webUrl: 'https://cocktail-catalog.netlify.app',
        mainImage: require('./images/johnlewis.jpg'),
        productImagesOptions: { width: 6, height: 8, cropX: 0, cropY: 0 },
        descriptions: [
            {
                language: 'ua',
                name: 'UA name',
                description: 'UA description',
                friendlyUrl: 'UA description',
                keyWords: 'UA description',
                highlights: 'UA description',
                metaDescription: 'UA description',
                title: 'Магазин жiночого одягу',
            },
            {
                language: 'en',
                name: 'EN name',
                description: 'EN description',
                friendlyUrl: 'EN description',
                keyWords: 'EN description',
                highlights: 'EN description',
                metaDescription: 'EN description',
                title: 'Store of Women`s Clothes',
            },
            {
                language: 'es',
                name: 'ES name',
                description: 'ES description',
                friendlyUrl: 'ES description',
                keyWords: 'ES description',
                highlights: 'ES description',
                metaDescription: 'ES description',
                title: 'Tienda de ropa de mujer',
            },
        ],
        mainStoreSettings: {
            skuSearch: true,
            colors: true,
            prices: true,
            sizes: true,
            contacts: true,
            categories: true,
            browserSearch: true,
            productShare: true,
        },
        additionalStoreSettings: {
            cart: true,
            favorites: true,
            promo: true,
            video: false,
            tableSizes: false,
            callback: true,
            platformAvailable: true,
            appleStore: true,
            playMarket: true,
        },
        dataBaseStoreSettings: { users: 5, products: 50, productModels: 5, photos: 5, videos: 1 },
        securityStoreSettings: { private: false, securityKey: null },
        storeProductTypes: [
            {
                code: 'Women clothes',
            },
        ],
        managers: [
            {
                firstName: 'Dmytro',
                lastName: 'Orgish',
                emailAddress: 'dmytro.orgish88@gmail.com',
                options: { manager: true },
                contacts: {
                    emailAddress: 'dmytro.orgish88@gmail.com',
                    phone: '+380665738771',
                    viber: '+380665738771',
                    whatsapp: '+380665738771',
                    telegram: 'https://t.me/@DmytroOrgish',
                },
            },
        ],
    },
    {
        code: 'DUNE',
        webUrl: 'https://cocktail-catalog.netlify.app',
        mainImage: require('./images/dune.jpg'),
        productImagesOptions: { width: 6, height: 8, cropX: 0, cropY: 0 },
        descriptions: [
            {
                language: 'ua',
                name: 'UA name',
                description: 'UA description',
                friendlyUrl: 'UA description',
                keyWords: 'UA description',
                highlights: 'UA description',
                metaDescription: 'UA description',
                title: 'Магазин чоловiчого взуття',
            },
            {
                language: 'en',
                name: 'EN name',
                description: 'EN description',
                friendlyUrl: 'EN description',
                keyWords: 'EN description',
                highlights: 'EN description',
                metaDescription: 'EN description',
                title: 'Store of Man`s Clothes',
            },
        ],
        mainStoreSettings: {
            skuSearch: true,
            colors: true,
            prices: true,
            sizes: true,
            contacts: true,
            categories: true,
            browserSearch: true,
            productShare: true,
        },
        additionalStoreSettings: {
            cart: true,
            favorites: true,
            promo: true,
            video: false,
            tableSizes: false,
            callback: false,
            platformAvailable: true,
            appleStore: true,
            playMarket: true,
        },
        dataBaseStoreSettings: { users: 2, products: 50, productModels: 5, photos: 5, videos: 1 },
        securityStoreSettings: { private: false, securityKey: null },
        storeProductTypes: [
            {
                code: 'Men clothes',
            },
            {
                code: 'Shoes',
            },
        ],
        managers: [
            {
                firstName: 'Dmytro',
                lastName: 'Orgish',
                emailAddress: 'dmytro.orgish88@gmail.com',
                options: { manager: true },
                contacts: {
                    emailAddress: 'dmytro.orgish88@gmail.com',
                    phone: '+380665738771',
                    viber: '+380665738771',
                    whatsapp: '+380665738771',
                    telegram: 'https://t.me/@DmytroOrgish',
                },
            },
        ],
    },
    {
        code: 'HATS',
        webUrl: 'https://cocktail-catalog.netlify.app',
        mainImage: require('./images/hats.jpeg'),
        productImagesOptions: { width: 6, height: 8, cropX: 0, cropY: 0 },
        descriptions: [
            {
                language: 'ua',
                name: 'UA name',
                description: 'UA description',
                friendlyUrl: 'UA description',
                keyWords: 'UA description',
                highlights: 'UA description',
                metaDescription: 'UA description',
                title: 'Магазин Головних Уборiв',
            },
            {
                language: 'en',
                name: 'EN name',
                description: 'EN description',
                friendlyUrl: 'EN description',
                keyWords: 'EN description',
                highlights: 'EN description',
                metaDescription: 'EN description',
                title: 'Store of Hats',
            },
        ],
        mainStoreSettings: {
            skuSearch: true,
            colors: true,
            prices: true,
            sizes: true,
            contacts: true,
            categories: true,
            browserSearch: true,
            productShare: true,
        },
        additionalStoreSettings: {
            cart: true,
            favorites: true,
            promo: true,
            video: false,
            tableSizes: false,
            callback: true,
            platformAvailable: true,
            appleStore: true,
            playMarket: true,
        },
        dataBaseStoreSettings: { users: 2, products: 50, productModels: 5, photos: 5, videos: 1 },
        securityStoreSettings: { private: false, securityKey: null },
        storeProductTypes: [
            {
                code: 'Men clothes',
            },
            {
                code: 'Hats',
            },
            { code: 'Women clothes' },
        ],
        managers: [
            {
                firstName: 'Dmytro',
                lastName: 'Orgish',
                emailAddress: 'dmytro.orgish88@gmail.com',
                options: { manager: true },
                contacts: {
                    emailAddress: 'dmytro.orgish88@gmail.com',
                    phone: '+380665738771',
                    viber: '+380665738771',
                    whatsapp: '+380665738771',
                    telegram: 'https://t.me/@DmytroOrgish',
                },
            },
        ],
    },
    {
        code: 'CoatsAndJackets',
        webUrl: 'https://cocktail-catalog.netlify.app',
        mainImage: require('./images/coatsandjackets.jpg'),
        productImagesOptions: { width: 6, height: 8, cropX: 0, cropY: 0 },
        descriptions: [
            {
                language: 'ua',
                name: 'UA name',
                description: 'UA description',
                friendlyUrl: 'UA description',
                keyWords: 'UA description',
                highlights: 'UA description',
                metaDescription: 'UA description',
                title: 'Магазин Чоловiчого Верхнього Одягу',
            },
            {
                language: 'en',
                name: 'EN name',
                description: 'EN description',
                friendlyUrl: 'EN description',
                keyWords: 'EN description',
                highlights: 'EN description',
                metaDescription: 'EN description',
                title: 'Store of Men`s Coats and Jackets',
            },
        ],
        mainStoreSettings: {
            skuSearch: true,
            colors: true,
            prices: true,
            sizes: true,
            contacts: true,
            categories: true,
            browserSearch: true,
            productShare: true,
        },
        additionalStoreSettings: {
            cart: true,
            favorites: true,
            promo: true,
            video: false,
            tableSizes: false,
            callback: true,
            platformAvailable: true,
            appleStore: true,
            playMarket: true,
        },
        dataBaseStoreSettings: { users: 2, products: 50, productModels: 5, photos: 5, videos: 1 },
        securityStoreSettings: { private: false, securityKey: null },
        storeProductTypes: [
            {
                code: 'Men clothes',
            },
            {
                code: 'Outerwear',
            },
        ],
        managers: [
            {
                firstName: 'Dmytro',
                lastName: 'Orgish',
                emailAddress: 'dmytro.orgish88@gmail.com',
                options: { manager: true },
                contacts: {
                    emailAddress: 'dmytro.orgish88@gmail.com',
                    phone: '+380665738771',
                    viber: '+380665738771',
                    whatsapp: '+380665738771',
                    telegram: 'https://t.me/@DmytroOrgish',
                },
            },
        ],
    },
    {
        code: 'WomanCoatsAndJackets',
        webUrl: 'https://cocktail-catalog.netlify.app',
        mainImage: require('./images/spring-jacket-women-1583332991.jpg'),
        productImagesOptions: { width: 6, height: 8, cropX: 0, cropY: 0 },
        descriptions: [
            {
                language: 'ua',
                name: 'UA name',
                description: 'UA description',
                friendlyUrl: 'UA description',
                keyWords: 'UA description',
                highlights: 'UA description',
                metaDescription: 'UA description',
                title: 'Магазин Жiночого Верхнього Одягу',
            },
            {
                language: 'en',
                name: 'EN name',
                description: 'EN description',
                friendlyUrl: 'EN description',
                keyWords: 'EN description',
                highlights: 'EN description',
                metaDescription: 'EN description',
                title: 'Store of Womens`s Coats and Jackets',
            },
        ],
        mainStoreSettings: {
            skuSearch: true,
            colors: true,
            prices: true,
            sizes: true,
            contacts: true,
            categories: true,
            browserSearch: true,
            productShare: true,
        },
        additionalStoreSettings: {
            cart: true,
            favorites: true,
            promo: true,
            video: false,
            tableSizes: false,
            callback: true,
            platformAvailable: true,
            appleStore: true,
            playMarket: true,
        },
        dataBaseStoreSettings: { users: 2, products: 50, productModels: 5, photos: 5, videos: 1 },
        securityStoreSettings: { private: false, securityKey: null },
        storeProductTypes: [
            {
                code: 'Women clothes',
            },
            {
                code: 'Outerwear',
            },
        ],
        managers: [
            {
                firstName: 'Dmytro',
                lastName: 'Orgish',
                emailAddress: 'dmytro.orgish88@gmail.com',
                options: { manager: true },
                contacts: {
                    emailAddress: 'dmytro.orgish88@gmail.com',
                    phone: '+380665738771',
                    viber: '+380665738771',
                    whatsapp: '+380665738771',
                    telegram: 'https://t.me/@DmytroOrgish',
                },
            },
        ],
    },
    {
        code: 'Textil',
        webUrl: 'https://cocktail-catalog.netlify.app',
        mainImage: require('./images/Textil.jpg'),
        productImagesOptions: { width: 6, height: 8, cropX: 0, cropY: 0 },
        descriptions: [
            {
                language: 'ua',
                name: 'UA name',
                description: 'UA description',
                friendlyUrl: 'UA description',
                keyWords: 'UA description',
                highlights: 'UA description',
                metaDescription: 'UA description',
                title: 'Магазин Текстилю',
            },
            {
                language: 'en',
                name: 'EN name',
                description: 'EN description',
                friendlyUrl: 'EN description',
                keyWords: 'EN description',
                highlights: 'EN description',
                metaDescription: 'EN description',
                title: 'Store of Textile',
            },
        ],
        mainStoreSettings: {
            skuSearch: true,
            colors: true,
            prices: true,
            sizes: false,
            contacts: true,
            categories: true,
            browserSearch: true,
            productShare: true,
        },
        additionalStoreSettings: {
            cart: true,
            favorites: true,
            promo: true,
            video: false,
            tableSizes: false,
            callback: true,
            platformAvailable: true,
            appleStore: true,
            playMarket: true,
        },
        dataBaseStoreSettings: { users: 2, products: 50, productModels: 5, photos: 5, videos: 1 },
        securityStoreSettings: { private: false, securityKey: null },
        storeProductTypes: [
            {
                code: 'Textile',
            },
        ],
        managers: [
            {
                firstName: 'Dmytro',
                lastName: 'Orgish',
                emailAddress: 'dmytro.orgish88@gmail.com',
                options: { manager: true },
                contacts: {
                    emailAddress: 'dmytro.orgish88@gmail.com',
                    phone: '+380665738771',
                    viber: '+380665738771',
                    whatsapp: '+380665738771',
                    telegram: 'https://t.me/@DmytroOrgish',
                },
            },
        ],
    },
];
