export const ALBERTO_BINI_MAIN_DB = {
    code: 'ALBERTO_BINI',
    appStoreUrl: '',
    playMarketUrl: '',
    webUrl: 'https://alberto-bini.netlify.app',
    mainImage: require('../images/posters/alb.jpeg'),
    productImagesOptions: { width: 6, height: 9, cropX: 0, cropY: 200 },
    links: [],
    descriptions: [
        {
            language: 'ua',
            name: 'Магазин жiночого одягу',
            description: 'Магазин жiночого одягу',
            friendlyUrl: 'Магазин жiночого одягу',
            keyWords: 'Магазин жiночого одягу',
            highlights: 'Магазин жiночого одягу',
            metaDescription: 'Магазин жiночого одягу',
            title: 'Магазин жiночого одягу',
        },
        {
            language: 'en',
            name: 'Store of Women`s Clothes',
            description: 'Store of Women`s Clothes',
            friendlyUrl: 'Store of Women`s Clothes',
            keyWords: 'Store of Women`s Clothes',
            highlights: 'Store of Women`s Clothes',
            metaDescription: 'Store of Women`s Clothes',
            title: 'Store of Women`s Clothes',
        },
        {
            language: 'ru',
            name: 'Магазин Женской Одежды',
            description: 'Магазин Женской Одежды',
            friendlyUrl: 'Магазин Женской Одежды',
            keyWords: 'Магазин Женской Одежды',
            highlights: 'Магазин Женской Одежды',
            metaDescription: 'Магазин Женской Одежды',
            title: 'Магазин Женской Одежды',
        },
    ],
    mainStoreSettings: {
        skuSearch: true,
        colors: true,
        prices: true,
        sizes: true,
        contacts: true,
        categories: true,
        browserSearch: true,
        productShare: true,
    },
    additionalStoreSettings: {
        cart: true,
        favorites: true,
        promo: true,
        video: false,
        tableSizes: true,
        callback: true,
        platformAvailable: true,
        appleStore: false,
        playMarket: false,
    },
    dataBaseStoreSettings: { users: 5, products: 200, productModels: 10, photos: 10, videos: 1 },
    securityStoreSettings: { private: false, securityKey: null },
    storeProductTypes: [
        {
            code: 'Outerwear',
        },
        {
            code: 'Women clothes',
        },
    ],
    managers: [
        {
            firstName: 'Alberto Bini Manager',
            lastName: '',
            emailAddress: '',
            options: { manager: true },
            contacts: {
                emailAddress: '',
                phone: '+380983080085',
                viber: '+380983080085',
                whatsapp: '+380983080085',
                telegram: 'Albertobiniopt',
            },
        },
    ],
};
