export const KREMEN_BELTS_MAIN_DB = {
    code: 'DEFAULT',
    webUrl: 'https://kremen-belts.netlify.app',
    appStoreUrl: '',
    playMarketUrl: '',
    mainImage: require('./images/belts.jpeg'),
    productImagesOptions: { width: 4, height: 3, cropX: 0, cropY: 0 },
    descriptions: [
        {
            language: 'ua',
            name: 'Кремен Белтс',
            description: 'Магазин ременiв',
            friendlyUrl: 'Магазин ременiв',
            keyWords: 'Магазин ременiв',
            highlights: 'Магазин ременiв',
            metaDescription: 'Магазин ременiв',
            title: 'Магазин ременiв',
        },
        {
            language: 'en',
            name: 'Kremen Belts',
            description: 'Belts Store',
            friendlyUrl: 'Belts Store',
            keyWords: 'Belts Store',
            highlights: 'Belts Store',
            metaDescription: 'Belts Store',
            title: 'Store of Belts',
        },
        {
            language: 'ru',
            name: 'Кремень Белтс',
            description: 'Магазин ремней',
            friendlyUrl: 'Магазин ремней',
            keyWords: 'Магазин ремней',
            highlights: 'Магазин ремней',
            metaDescription: 'Магазин ремней',
            title: 'Магазин ремней и аксессуаров из кожи',
        },
    ],
    mainStoreSettings: {
        skuSearch: true,
        colors: true,
        prices: true,
        sizes: false,
        contacts: true,
        categories: true,
        browserSearch: true,
        productShare: true,
        platformAvailable: true,
    },
    additionalStoreSettings: {
        cart: true,
        favorites: true,
        promo: true,
        video: false,
        tableSizes: false,
        callback: false,
        appleStore: false,
        playMarket: false,
        analytics: false,
    },
    dataBaseStoreSettings: {
        users: 'unlimited',
        products: 'unlimited',
        productModels: 'unlimited',
        photos: 10,
        videos: 1,
    },
    securityStoreSettings: { private: false, securityKey: null },
    storeProductTypes: [{ code: 'Men clothes' }, { code: 'Women clothes' }, { code: 'Belts' }],
    managers: [
        {
            firstName: 'Sergey',
            lastName: '',
            emailAddress: 'Kremen.katalog@gmail.com',
            options: { manager: true },
            contacts: {
                emailAddress: 'Kremen.katalog@gmail.com',
                phone: '+380660355716',
                viber: '+380660355716',
                whatsapp: '+380660355716',
                telegram: '',
            },
        },
    ],
};
